version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule: { interval: weekly }
    groups:
      frontend-non-major:
        patterns: ["*"]
        update-types: ["minor", "patch"]
  - package-ecosystem: gomod
    directory: /api
    schedule: { interval: weekly }
    groups:
      go-non-major:
        patterns: ["*"]
        update-types: ["minor", "patch"]
  - package-ecosystem: github-actions
    directory: /
    schedule: { interval: weekly }
  - package-ecosystem: terraform
    directory: /infra/environments/staging
    schedule: { interval: weekly }
  - package-ecosystem: terraform
    directory: /infra/environments/production
    schedule: { interval: weekly }
  - package-ecosystem: terraform
    directory: /infra/global
    schedule: { interval: weekly }
