// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: applications.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createApplication = `-- name: CreateApplication :one
INSERT INTO ats.applications (cycle_id, form_id, applicant_user_id)
SELECT cycles.id, forms.id, $1
FROM ats.application_cycles AS cycles
JOIN ats.application_forms AS forms
    ON forms.cycle_id = cycles.id
   AND forms.published_at IS NOT NULL
WHERE forms.id = $2
  AND cycles.active
  AND cycles.applications_open_at <= CURRENT_TIMESTAMP
  AND CURRENT_TIMESTAMP < cycles.applications_close_at
ON CONFLICT (cycle_id, applicant_user_id) DO UPDATE
SET updated_at = ats.applications.updated_at
RETURNING id
`

type CreateApplicationParams struct {
	ApplicantUserID pgtype.UUID `json:"applicant_user_id"`
	FormID          pgtype.UUID `json:"form_id"`
}

func (q *Queries) CreateApplication(ctx context.Context, arg CreateApplicationParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, createApplication, arg.ApplicantUserID, arg.FormID)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}

const deleteApplicationAnswers = `-- name: DeleteApplicationAnswers :exec
DELETE FROM ats.application_answers
WHERE application_id = $1
`

func (q *Queries) DeleteApplicationAnswers(ctx context.Context, applicationID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteApplicationAnswers, applicationID)
	return err
}

const ensureIntakeFixtureCycle = `-- name: EnsureIntakeFixtureCycle :exec
INSERT INTO ats.application_cycles (
    id,
    slug,
    name,
    applications_open_at,
    applications_close_at,
    active
)
VALUES (
    $1,
    $2,
    $3,
    CURRENT_TIMESTAMP - INTERVAL '1 day',
    CURRENT_TIMESTAMP + INTERVAL '365 days',
    true
)
ON CONFLICT (id) DO UPDATE
SET slug = EXCLUDED.slug,
    name = EXCLUDED.name,
    applications_open_at = EXCLUDED.applications_open_at,
    applications_close_at = EXCLUDED.applications_close_at,
    active = true,
    updated_at = CURRENT_TIMESTAMP
`

type EnsureIntakeFixtureCycleParams struct {
	ID   pgtype.UUID `json:"id"`
	Slug string      `json:"slug"`
	Name string      `json:"name"`
}

func (q *Queries) EnsureIntakeFixtureCycle(ctx context.Context, arg EnsureIntakeFixtureCycleParams) error {
	_, err := q.db.Exec(ctx, ensureIntakeFixtureCycle, arg.ID, arg.Slug, arg.Name)
	return err
}

const ensureIntakeFixtureForm = `-- name: EnsureIntakeFixtureForm :exec
INSERT INTO ats.application_forms (
    id,
    cycle_id,
    version,
    schema_json,
    published_at,
    created_by
)
VALUES ($1, $2, 2, $3, CURRENT_TIMESTAMP, $4)
ON CONFLICT (cycle_id, version) DO UPDATE
SET schema_json = EXCLUDED.schema_json,
    published_at = EXCLUDED.published_at
WHERE ats.application_forms.published_at IS NULL
  AND NOT EXISTS (
      SELECT 1
      FROM ats.applications
      WHERE applications.form_id = ats.application_forms.id
  )
`

type EnsureIntakeFixtureFormParams struct {
	ID         pgtype.UUID `json:"id"`
	CycleID    pgtype.UUID `json:"cycle_id"`
	SchemaJson []byte      `json:"schema_json"`
	CreatedBy  pgtype.UUID `json:"created_by"`
}

func (q *Queries) EnsureIntakeFixtureForm(ctx context.Context, arg EnsureIntakeFixtureFormParams) error {
	_, err := q.db.Exec(ctx, ensureIntakeFixtureForm,
		arg.ID,
		arg.CycleID,
		arg.SchemaJson,
		arg.CreatedBy,
	)
	return err
}

const getApplicationForApplicant = `-- name: GetApplicationForApplicant :one
SELECT
    applications.id,
    applications.cycle_id,
    applications.form_id,
    applications.applicant_user_id,
    (
        CASE
            WHEN applications.status IN ('accepted', 'waitlisted', 'rejected') THEN 'submitted'
            ELSE applications.status
        END
    )::text AS status,
    applications.submitted_at,
    applications.withdrawn_at,
    applications.current_decision,
    applications.decision_released_at,
    applications.lock_version,
    applications.created_at,
    applications.updated_at,
    forms.version AS form_version,
    forms.schema_json,
    COALESCE(
        jsonb_object_agg(answers.question_key, answers.value_json)
            FILTER (WHERE answers.question_key IS NOT NULL),
        '{}'::jsonb
    )::text AS answers_json
FROM ats.applications AS applications
JOIN ats.application_forms AS forms ON forms.id = applications.form_id
LEFT JOIN ats.application_answers AS answers ON answers.application_id = applications.id
WHERE applications.id = $1
  AND applications.applicant_user_id = $2
GROUP BY
    applications.id,
    applications.cycle_id,
    applications.form_id,
    applications.applicant_user_id,
    applications.status,
    applications.submitted_at,
    applications.withdrawn_at,
    applications.current_decision,
    applications.decision_released_at,
    applications.lock_version,
    applications.created_at,
    applications.updated_at,
    forms.version,
    forms.schema_json
`

type GetApplicationForApplicantParams struct {
	ID              pgtype.UUID `json:"id"`
	ApplicantUserID pgtype.UUID `json:"applicant_user_id"`
}

type GetApplicationForApplicantRow struct {
	ID                 pgtype.UUID        `json:"id"`
	CycleID            pgtype.UUID        `json:"cycle_id"`
	FormID             pgtype.UUID        `json:"form_id"`
	ApplicantUserID    pgtype.UUID        `json:"applicant_user_id"`
	Status             string             `json:"status"`
	SubmittedAt        pgtype.Timestamptz `json:"submitted_at"`
	WithdrawnAt        pgtype.Timestamptz `json:"withdrawn_at"`
	CurrentDecision    pgtype.Text        `json:"current_decision"`
	DecisionReleasedAt pgtype.Timestamptz `json:"decision_released_at"`
	LockVersion        int32              `json:"lock_version"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
	UpdatedAt          pgtype.Timestamptz `json:"updated_at"`
	FormVersion        int32              `json:"form_version"`
	SchemaJson         []byte             `json:"schema_json"`
	AnswersJson        string             `json:"answers_json"`
}

func (q *Queries) GetApplicationForApplicant(ctx context.Context, arg GetApplicationForApplicantParams) (GetApplicationForApplicantRow, error) {
	row := q.db.QueryRow(ctx, getApplicationForApplicant, arg.ID, arg.ApplicantUserID)
	var i GetApplicationForApplicantRow
	err := row.Scan(
		&i.ID,
		&i.CycleID,
		&i.FormID,
		&i.ApplicantUserID,
		&i.Status,
		&i.SubmittedAt,
		&i.WithdrawnAt,
		&i.CurrentDecision,
		&i.DecisionReleasedAt,
		&i.LockVersion,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.FormVersion,
		&i.SchemaJson,
		&i.AnswersJson,
	)
	return i, err
}

const getCurrentApplicationForm = `-- name: GetCurrentApplicationForm :one
SELECT
    forms.id AS form_id,
    forms.version AS form_version,
    forms.schema_json,
    cycles.id AS cycle_id
FROM ats.application_cycles AS cycles
JOIN ats.application_forms AS forms
    ON forms.cycle_id = cycles.id
   AND forms.published_at IS NOT NULL
WHERE cycles.active
  AND cycles.applications_open_at <= CURRENT_TIMESTAMP
  AND CURRENT_TIMESTAMP < cycles.applications_close_at
ORDER BY forms.version DESC
LIMIT 1
`

type GetCurrentApplicationFormRow struct {
	FormID      pgtype.UUID `json:"form_id"`
	FormVersion int32       `json:"form_version"`
	SchemaJson  []byte      `json:"schema_json"`
	CycleID     pgtype.UUID `json:"cycle_id"`
}

func (q *Queries) GetCurrentApplicationForm(ctx context.Context) (GetCurrentApplicationFormRow, error) {
	row := q.db.QueryRow(ctx, getCurrentApplicationForm)
	var i GetCurrentApplicationFormRow
	err := row.Scan(
		&i.FormID,
		&i.FormVersion,
		&i.SchemaJson,
		&i.CycleID,
	)
	return i, err
}

const insertSubmissionConfirmation = `-- name: InsertSubmissionConfirmation :exec
INSERT INTO ats.email_outbox (
    event_type,
    recipient_user_id,
    recipient_email,
    template_key,
    template_data_json,
    dedupe_key
)
VALUES ('submission_confirmation', $1, $2, 'submission_confirmation', $3, $4)
ON CONFLICT (dedupe_key) DO NOTHING
`

type InsertSubmissionConfirmationParams struct {
	RecipientUserID  pgtype.UUID `json:"recipient_user_id"`
	RecipientEmail   string      `json:"recipient_email"`
	TemplateDataJson []byte      `json:"template_data_json"`
	DedupeKey        string      `json:"dedupe_key"`
}

func (q *Queries) InsertSubmissionConfirmation(ctx context.Context, arg InsertSubmissionConfirmationParams) error {
	_, err := q.db.Exec(ctx, insertSubmissionConfirmation,
		arg.RecipientUserID,
		arg.RecipientEmail,
		arg.TemplateDataJson,
		arg.DedupeKey,
	)
	return err
}

const isApplicationSubmissionWindowOpen = `-- name: IsApplicationSubmissionWindowOpen :one
SELECT EXISTS (
    SELECT 1
    FROM ats.applications AS applications
    JOIN ats.application_cycles AS cycles ON cycles.id = applications.cycle_id
    WHERE applications.id = $1
      AND applications.applicant_user_id = $2
      AND cycles.active
      AND cycles.applications_open_at <= CURRENT_TIMESTAMP
      AND CURRENT_TIMESTAMP < cycles.applications_close_at
) AS is_open
`

type IsApplicationSubmissionWindowOpenParams struct {
	ID              pgtype.UUID `json:"id"`
	ApplicantUserID pgtype.UUID `json:"applicant_user_id"`
}

func (q *Queries) IsApplicationSubmissionWindowOpen(ctx context.Context, arg IsApplicationSubmissionWindowOpenParams) (bool, error) {
	row := q.db.QueryRow(ctx, isApplicationSubmissionWindowOpen, arg.ID, arg.ApplicantUserID)
	var is_open bool
	err := row.Scan(&is_open)
	return is_open, err
}

const listApplicationsForApplicant = `-- name: ListApplicationsForApplicant :many
SELECT
    applications.id,
    applications.cycle_id,
    applications.form_id,
    (
        CASE
            WHEN applications.status IN ('accepted', 'waitlisted', 'rejected') THEN 'submitted'
            ELSE applications.status
        END
    )::text AS status,
    applications.submitted_at,
    applications.lock_version,
    applications.created_at,
    applications.updated_at,
    forms.version AS form_version,
    COALESCE(
        jsonb_object_agg(answers.question_key, answers.value_json)
            FILTER (WHERE answers.question_key IS NOT NULL),
        '{}'::jsonb
    )::text AS answers_json
FROM ats.applications AS applications
JOIN ats.application_forms AS forms ON forms.id = applications.form_id
LEFT JOIN ats.application_answers AS answers ON answers.application_id = applications.id
WHERE applications.applicant_user_id = $1
GROUP BY
    applications.id,
    applications.cycle_id,
    applications.form_id,
    applications.status,
    applications.submitted_at,
    applications.lock_version,
    applications.created_at,
    applications.updated_at,
    forms.version
ORDER BY applications.created_at DESC
`

type ListApplicationsForApplicantRow struct {
	ID          pgtype.UUID        `json:"id"`
	CycleID     pgtype.UUID        `json:"cycle_id"`
	FormID      pgtype.UUID        `json:"form_id"`
	Status      string             `json:"status"`
	SubmittedAt pgtype.Timestamptz `json:"submitted_at"`
	LockVersion int32              `json:"lock_version"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
	FormVersion int32              `json:"form_version"`
	AnswersJson string             `json:"answers_json"`
}

func (q *Queries) ListApplicationsForApplicant(ctx context.Context, applicantUserID pgtype.UUID) ([]ListApplicationsForApplicantRow, error) {
	rows, err := q.db.Query(ctx, listApplicationsForApplicant, applicantUserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListApplicationsForApplicantRow{}
	for rows.Next() {
		var i ListApplicationsForApplicantRow
		if err := rows.Scan(
			&i.ID,
			&i.CycleID,
			&i.FormID,
			&i.Status,
			&i.SubmittedAt,
			&i.LockVersion,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.FormVersion,
			&i.AnswersJson,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const otherActiveApplicationCycleExists = `-- name: OtherActiveApplicationCycleExists :one
SELECT EXISTS (
    SELECT 1
    FROM ats.application_cycles
    WHERE active
      AND id <> $1
)
`

func (q *Queries) OtherActiveApplicationCycleExists(ctx context.Context, id pgtype.UUID) (bool, error) {
	row := q.db.QueryRow(ctx, otherActiveApplicationCycleExists, id)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const replaceApplicationAnswers = `-- name: ReplaceApplicationAnswers :exec
INSERT INTO ats.application_answers (application_id, question_key, value_json)
SELECT $1, entry.key, entry.value
FROM pg_catalog.jsonb_each($2::jsonb) AS entry
ON CONFLICT (application_id, question_key) DO UPDATE
SET value_json = EXCLUDED.value_json,
    updated_at = CURRENT_TIMESTAMP
`

type ReplaceApplicationAnswersParams struct {
	ApplicationID pgtype.UUID `json:"application_id"`
	AnswersJson   []byte      `json:"answers_json"`
}

func (q *Queries) ReplaceApplicationAnswers(ctx context.Context, arg ReplaceApplicationAnswersParams) error {
	_, err := q.db.Exec(ctx, replaceApplicationAnswers, arg.ApplicationID, arg.AnswersJson)
	return err
}

const seedIntakeFixtureUser = `-- name: SeedIntakeFixtureUser :one
INSERT INTO ats.users (id, clerk_user_id, primary_email, display_name)
VALUES ($1, $2, $3, $4)
ON CONFLICT (clerk_user_id) DO UPDATE
SET primary_email = EXCLUDED.primary_email,
    display_name = EXCLUDED.display_name,
    updated_at = CURRENT_TIMESTAMP
RETURNING id
`

type SeedIntakeFixtureUserParams struct {
	ID           pgtype.UUID `json:"id"`
	ClerkUserID  string      `json:"clerk_user_id"`
	PrimaryEmail string      `json:"primary_email"`
	DisplayName  pgtype.Text `json:"display_name"`
}

func (q *Queries) SeedIntakeFixtureUser(ctx context.Context, arg SeedIntakeFixtureUserParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, seedIntakeFixtureUser,
		arg.ID,
		arg.ClerkUserID,
		arg.PrimaryEmail,
		arg.DisplayName,
	)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}

const updateApplicationDraft = `-- name: UpdateApplicationDraft :one
UPDATE ats.applications
SET lock_version = lock_version + 1,
    updated_at = CURRENT_TIMESTAMP
WHERE id = $1
  AND applicant_user_id = $2
  AND status = 'draft'
  AND lock_version = $3
RETURNING id
`

type UpdateApplicationDraftParams struct {
	ID              pgtype.UUID `json:"id"`
	ApplicantUserID pgtype.UUID `json:"applicant_user_id"`
	LockVersion     int32       `json:"lock_version"`
}

func (q *Queries) UpdateApplicationDraft(ctx context.Context, arg UpdateApplicationDraftParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, updateApplicationDraft, arg.ID, arg.ApplicantUserID, arg.LockVersion)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}

const updateApplicationSubmission = `-- name: UpdateApplicationSubmission :one
UPDATE ats.applications AS applications
SET status = 'submitted',
    submitted_at = CURRENT_TIMESTAMP,
    applicant_email_snapshot = $4,
    lock_version = applications.lock_version + 1,
    updated_at = CURRENT_TIMESTAMP
WHERE applications.id = $1
  AND applications.applicant_user_id = $2
  AND applications.status = 'draft'
  AND applications.lock_version = $3
  AND EXISTS (
      SELECT 1
      FROM ats.application_cycles AS cycles
      WHERE cycles.id = applications.cycle_id
        AND cycles.active
        AND cycles.applications_open_at <= CURRENT_TIMESTAMP
        AND CURRENT_TIMESTAMP < cycles.applications_close_at
  )
RETURNING id
`

type UpdateApplicationSubmissionParams struct {
	ID                     pgtype.UUID `json:"id"`
	ApplicantUserID        pgtype.UUID `json:"applicant_user_id"`
	LockVersion            int32       `json:"lock_version"`
	ApplicantEmailSnapshot pgtype.Text `json:"applicant_email_snapshot"`
}

func (q *Queries) UpdateApplicationSubmission(ctx context.Context, arg UpdateApplicationSubmissionParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, updateApplicationSubmission,
		arg.ID,
		arg.ApplicantUserID,
		arg.LockVersion,
		arg.ApplicantEmailSnapshot,
	)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}
