// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: decisions.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getLatestDecisionForApplication = `-- name: GetLatestDecisionForApplication :one
SELECT
    decision.id,
    decision.application_id,
    decision.outcome,
    decision.internal_reason,
    decision.decided_by,
    decision.decided_at,
    decision.released_by,
    decision.released_at,
    decision.supersedes_id,
    decision.created_at
FROM ats.decisions AS decision
WHERE decision.id = (
    SELECT applications.current_decision_id
    FROM ats.applications AS applications
    WHERE applications.id = $1
)
`

func (q *Queries) GetLatestDecisionForApplication(ctx context.Context, id pgtype.UUID) (AtsDecision, error) {
	row := q.db.QueryRow(ctx, getLatestDecisionForApplication, id)
	var i AtsDecision
	err := row.Scan(
		&i.ID,
		&i.ApplicationID,
		&i.Outcome,
		&i.InternalReason,
		&i.DecidedBy,
		&i.DecidedAt,
		&i.ReleasedBy,
		&i.ReleasedAt,
		&i.SupersedesID,
		&i.CreatedAt,
	)
	return i, err
}

const getReleasedDecisionForApplicant = `-- name: GetReleasedDecisionForApplicant :one
SELECT
    decisions.application_id,
    decisions.outcome,
    decisions.released_at
FROM ats.applications
JOIN ats.decisions ON decisions.application_id = applications.id
WHERE applications.id = $1
  AND applications.applicant_user_id = $2
  AND applications.decision_released_at IS NOT NULL
  AND decisions.released_at IS NOT NULL
  AND decisions.id = applications.current_decision_id
`

type GetReleasedDecisionForApplicantParams struct {
	ID              pgtype.UUID `json:"id"`
	ApplicantUserID pgtype.UUID `json:"applicant_user_id"`
}

type GetReleasedDecisionForApplicantRow struct {
	ApplicationID pgtype.UUID        `json:"application_id"`
	Outcome       string             `json:"outcome"`
	ReleasedAt    pgtype.Timestamptz `json:"released_at"`
}

func (q *Queries) GetReleasedDecisionForApplicant(ctx context.Context, arg GetReleasedDecisionForApplicantParams) (GetReleasedDecisionForApplicantRow, error) {
	row := q.db.QueryRow(ctx, getReleasedDecisionForApplicant, arg.ID, arg.ApplicantUserID)
	var i GetReleasedDecisionForApplicantRow
	err := row.Scan(&i.ApplicationID, &i.Outcome, &i.ReleasedAt)
	return i, err
}

const insertAttendeeCreatedAudit = `-- name: InsertAttendeeCreatedAudit :exec
INSERT INTO ats.audit_events (actor_user_id, event_type, subject_type, subject_id, metadata_json)
VALUES ($1, 'attendee_created', 'attendee', $2, jsonb_build_object('applicationId', $3::text))
`

type InsertAttendeeCreatedAuditParams struct {
	ActorUserID   pgtype.UUID `json:"actor_user_id"`
	SubjectID     pgtype.UUID `json:"subject_id"`
	ApplicationID string      `json:"application_id"`
}

func (q *Queries) InsertAttendeeCreatedAudit(ctx context.Context, arg InsertAttendeeCreatedAuditParams) error {
	_, err := q.db.Exec(ctx, insertAttendeeCreatedAudit, arg.ActorUserID, arg.SubjectID, arg.ApplicationID)
	return err
}

const insertDecision = `-- name: InsertDecision :one
INSERT INTO ats.decisions (
    application_id,
    outcome,
    internal_reason,
    decided_by,
    supersedes_id
)
VALUES ($1, $2, $3, $4, $5)
RETURNING
    id,
    application_id,
    outcome,
    internal_reason,
    decided_by,
    decided_at,
    released_by,
    released_at,
    supersedes_id,
    created_at
`

type InsertDecisionParams struct {
	ApplicationID  pgtype.UUID `json:"application_id"`
	Outcome        string      `json:"outcome"`
	InternalReason pgtype.Text `json:"internal_reason"`
	DecidedBy      pgtype.UUID `json:"decided_by"`
	SupersedesID   pgtype.UUID `json:"supersedes_id"`
}

func (q *Queries) InsertDecision(ctx context.Context, arg InsertDecisionParams) (AtsDecision, error) {
	row := q.db.QueryRow(ctx, insertDecision,
		arg.ApplicationID,
		arg.Outcome,
		arg.InternalReason,
		arg.DecidedBy,
		arg.SupersedesID,
	)
	var i AtsDecision
	err := row.Scan(
		&i.ID,
		&i.ApplicationID,
		&i.Outcome,
		&i.InternalReason,
		&i.DecidedBy,
		&i.DecidedAt,
		&i.ReleasedBy,
		&i.ReleasedAt,
		&i.SupersedesID,
		&i.CreatedAt,
	)
	return i, err
}

const insertDecisionRecordedAudit = `-- name: InsertDecisionRecordedAudit :exec
INSERT INTO ats.audit_events (actor_user_id, event_type, subject_type, subject_id, metadata_json)
VALUES ($1, 'decision_recorded', 'decision', $2, jsonb_build_object('applicationId', $3::text, 'outcome', $4::text))
`

type InsertDecisionRecordedAuditParams struct {
	ActorUserID   pgtype.UUID `json:"actor_user_id"`
	SubjectID     pgtype.UUID `json:"subject_id"`
	ApplicationID string      `json:"application_id"`
	Outcome       string      `json:"outcome"`
}

func (q *Queries) InsertDecisionRecordedAudit(ctx context.Context, arg InsertDecisionRecordedAuditParams) error {
	_, err := q.db.Exec(ctx, insertDecisionRecordedAudit,
		arg.ActorUserID,
		arg.SubjectID,
		arg.ApplicationID,
		arg.Outcome,
	)
	return err
}

const insertDecisionReleaseEmail = `-- name: InsertDecisionReleaseEmail :exec
INSERT INTO ats.email_outbox (
    event_type,
    recipient_user_id,
    recipient_email,
    template_key,
    template_data_json,
    dedupe_key
)
VALUES ('decision_release', $1, $2, 'decision_release', $3, $4)
ON CONFLICT (dedupe_key) DO NOTHING
`

type InsertDecisionReleaseEmailParams struct {
	RecipientUserID  pgtype.UUID `json:"recipient_user_id"`
	RecipientEmail   string      `json:"recipient_email"`
	TemplateDataJson []byte      `json:"template_data_json"`
	DedupeKey        string      `json:"dedupe_key"`
}

func (q *Queries) InsertDecisionReleaseEmail(ctx context.Context, arg InsertDecisionReleaseEmailParams) error {
	_, err := q.db.Exec(ctx, insertDecisionReleaseEmail,
		arg.RecipientUserID,
		arg.RecipientEmail,
		arg.TemplateDataJson,
		arg.DedupeKey,
	)
	return err
}

const insertDecisionReleasedAudit = `-- name: InsertDecisionReleasedAudit :exec
INSERT INTO ats.audit_events (actor_user_id, event_type, subject_type, subject_id, metadata_json)
VALUES ($1, 'decision_released', 'decision', $2, jsonb_build_object('applicationId', $3::text, 'outcome', $4::text))
`

type InsertDecisionReleasedAuditParams struct {
	ActorUserID   pgtype.UUID `json:"actor_user_id"`
	SubjectID     pgtype.UUID `json:"subject_id"`
	ApplicationID string      `json:"application_id"`
	Outcome       string      `json:"outcome"`
}

func (q *Queries) InsertDecisionReleasedAudit(ctx context.Context, arg InsertDecisionReleasedAuditParams) error {
	_, err := q.db.Exec(ctx, insertDecisionReleasedAudit,
		arg.ActorUserID,
		arg.SubjectID,
		arg.ApplicationID,
		arg.Outcome,
	)
	return err
}

const lockApplicationForDecision = `-- name: LockApplicationForDecision :one
SELECT
    applications.id,
    applications.cycle_id,
    applications.applicant_user_id,
    applications.status,
    applications.current_decision_id,
    applicants.primary_email AS applicant_email,
    COALESCE(NULLIF(applicants.display_name, ''), applicants.primary_email) AS applicant_display_name
FROM ats.applications AS applications
JOIN ats.users AS applicants ON applicants.id = applications.applicant_user_id
WHERE applications.id = $1
FOR UPDATE OF applications
`

type LockApplicationForDecisionRow struct {
	ID                   pgtype.UUID `json:"id"`
	CycleID              pgtype.UUID `json:"cycle_id"`
	ApplicantUserID      pgtype.UUID `json:"applicant_user_id"`
	Status               string      `json:"status"`
	CurrentDecisionID    pgtype.UUID `json:"current_decision_id"`
	ApplicantEmail       string      `json:"applicant_email"`
	ApplicantDisplayName string      `json:"applicant_display_name"`
}

func (q *Queries) LockApplicationForDecision(ctx context.Context, id pgtype.UUID) (LockApplicationForDecisionRow, error) {
	row := q.db.QueryRow(ctx, lockApplicationForDecision, id)
	var i LockApplicationForDecisionRow
	err := row.Scan(
		&i.ID,
		&i.CycleID,
		&i.ApplicantUserID,
		&i.Status,
		&i.CurrentDecisionID,
		&i.ApplicantEmail,
		&i.ApplicantDisplayName,
	)
	return i, err
}

const lockCurrentDecisionForRelease = `-- name: LockCurrentDecisionForRelease :one
SELECT
    decision.id,
    decision.application_id,
    decision.outcome,
    decision.internal_reason,
    decision.decided_by,
    decision.decided_at,
    decision.released_by,
    decision.released_at,
    decision.supersedes_id,
    decision.created_at,
    applications.applicant_user_id,
    applicants.primary_email AS applicant_email
FROM ats.decisions AS decision
JOIN ats.applications AS applications ON applications.id = decision.application_id
JOIN ats.users AS applicants ON applicants.id = applications.applicant_user_id
WHERE decision.id = $1
  AND applications.current_decision_id = decision.id
FOR UPDATE OF decision, applications
`

type LockCurrentDecisionForReleaseRow struct {
	ID              pgtype.UUID        `json:"id"`
	ApplicationID   pgtype.UUID        `json:"application_id"`
	Outcome         string             `json:"outcome"`
	InternalReason  pgtype.Text        `json:"internal_reason"`
	DecidedBy       pgtype.UUID        `json:"decided_by"`
	DecidedAt       pgtype.Timestamptz `json:"decided_at"`
	ReleasedBy      pgtype.UUID        `json:"released_by"`
	ReleasedAt      pgtype.Timestamptz `json:"released_at"`
	SupersedesID    pgtype.UUID        `json:"supersedes_id"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	ApplicantUserID pgtype.UUID        `json:"applicant_user_id"`
	ApplicantEmail  string             `json:"applicant_email"`
}

func (q *Queries) LockCurrentDecisionForRelease(ctx context.Context, id pgtype.UUID) (LockCurrentDecisionForReleaseRow, error) {
	row := q.db.QueryRow(ctx, lockCurrentDecisionForRelease, id)
	var i LockCurrentDecisionForReleaseRow
	err := row.Scan(
		&i.ID,
		&i.ApplicationID,
		&i.Outcome,
		&i.InternalReason,
		&i.DecidedBy,
		&i.DecidedAt,
		&i.ReleasedBy,
		&i.ReleasedAt,
		&i.SupersedesID,
		&i.CreatedAt,
		&i.ApplicantUserID,
		&i.ApplicantEmail,
	)
	return i, err
}

const releaseDecision = `-- name: ReleaseDecision :one
UPDATE ats.decisions
SET released_by = $2,
    released_at = CURRENT_TIMESTAMP
WHERE id = $1
  AND released_at IS NULL
RETURNING released_at
`

type ReleaseDecisionParams struct {
	ID         pgtype.UUID `json:"id"`
	ReleasedBy pgtype.UUID `json:"released_by"`
}

func (q *Queries) ReleaseDecision(ctx context.Context, arg ReleaseDecisionParams) (pgtype.Timestamptz, error) {
	row := q.db.QueryRow(ctx, releaseDecision, arg.ID, arg.ReleasedBy)
	var released_at pgtype.Timestamptz
	err := row.Scan(&released_at)
	return released_at, err
}

const seedAttendeeHackerRole = `-- name: SeedAttendeeHackerRole :exec
INSERT INTO ats.attendee_roles (attendee_id, role)
VALUES ($1, 'hacker')
ON CONFLICT (attendee_id, role) DO NOTHING
`

func (q *Queries) SeedAttendeeHackerRole(ctx context.Context, attendeeID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, seedAttendeeHackerRole, attendeeID)
	return err
}

const updateApplicationDecisionCache = `-- name: UpdateApplicationDecisionCache :exec
UPDATE ats.applications
SET status = $2,
    current_decision = $2,
    current_decision_id = $3,
    decision_released_at = NULL,
    updated_at = CURRENT_TIMESTAMP
WHERE id = $1
`

type UpdateApplicationDecisionCacheParams struct {
	ID                pgtype.UUID `json:"id"`
	Status            string      `json:"status"`
	CurrentDecisionID pgtype.UUID `json:"current_decision_id"`
}

func (q *Queries) UpdateApplicationDecisionCache(ctx context.Context, arg UpdateApplicationDecisionCacheParams) error {
	_, err := q.db.Exec(ctx, updateApplicationDecisionCache, arg.ID, arg.Status, arg.CurrentDecisionID)
	return err
}

const updateApplicationDecisionRelease = `-- name: UpdateApplicationDecisionRelease :exec
UPDATE ats.applications
SET decision_released_at = $2,
    updated_at = CURRENT_TIMESTAMP
WHERE id = $1
`

type UpdateApplicationDecisionReleaseParams struct {
	ID                 pgtype.UUID        `json:"id"`
	DecisionReleasedAt pgtype.Timestamptz `json:"decision_released_at"`
}

func (q *Queries) UpdateApplicationDecisionRelease(ctx context.Context, arg UpdateApplicationDecisionReleaseParams) error {
	_, err := q.db.Exec(ctx, updateApplicationDecisionRelease, arg.ID, arg.DecisionReleasedAt)
	return err
}

const upsertAcceptedAttendee = `-- name: UpsertAcceptedAttendee :one
WITH inserted AS (
    INSERT INTO ats.attendees (
        cycle_id,
        application_id,
        user_id,
        display_name,
        email
    )
    VALUES ($1, $2, $3, $4, $5)
    ON CONFLICT (application_id) DO NOTHING
    RETURNING id
), attendee AS (
    SELECT id, true AS attendee_created FROM inserted
    UNION ALL
    SELECT attendees.id, false AS attendee_created
    FROM ats.attendees
    WHERE attendees.application_id = $2
      AND NOT EXISTS (SELECT 1 FROM inserted)
)
SELECT id, attendee_created
FROM attendee
`

type UpsertAcceptedAttendeeParams struct {
	CycleID       pgtype.UUID `json:"cycle_id"`
	ApplicationID pgtype.UUID `json:"application_id"`
	UserID        pgtype.UUID `json:"user_id"`
	DisplayName   string      `json:"display_name"`
	Email         string      `json:"email"`
}

type UpsertAcceptedAttendeeRow struct {
	ID              pgtype.UUID `json:"id"`
	AttendeeCreated bool        `json:"attendee_created"`
}

func (q *Queries) UpsertAcceptedAttendee(ctx context.Context, arg UpsertAcceptedAttendeeParams) (UpsertAcceptedAttendeeRow, error) {
	row := q.db.QueryRow(ctx, upsertAcceptedAttendee,
		arg.CycleID,
		arg.ApplicationID,
		arg.UserID,
		arg.DisplayName,
		arg.Email,
	)
	var i UpsertAcceptedAttendeeRow
	err := row.Scan(&i.ID, &i.AttendeeCreated)
	return i, err
}
