// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: identity.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const acquireOrganizerBootstrapLock = `-- name: AcquireOrganizerBootstrapLock :exec
SELECT pg_advisory_xact_lock(740159346019)
`

func (q *Queries) AcquireOrganizerBootstrapLock(ctx context.Context) error {
	_, err := q.db.Exec(ctx, acquireOrganizerBootstrapLock)
	return err
}

const assignUserRole = `-- name: AssignUserRole :exec
INSERT INTO ats.user_roles (user_id, role, created_by)
VALUES ($1, $2, $3)
ON CONFLICT (user_id, role) DO NOTHING
`

type AssignUserRoleParams struct {
	UserID    pgtype.UUID `json:"user_id"`
	Role      string      `json:"role"`
	CreatedBy pgtype.UUID `json:"created_by"`
}

func (q *Queries) AssignUserRole(ctx context.Context, arg AssignUserRoleParams) error {
	_, err := q.db.Exec(ctx, assignUserRole, arg.UserID, arg.Role, arg.CreatedBy)
	return err
}

const countOrganizerRoles = `-- name: CountOrganizerRoles :one
SELECT count(*)
FROM ats.user_roles
WHERE role = 'organizer'
`

func (q *Queries) CountOrganizerRoles(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countOrganizerRoles)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const ensureApplicantRole = `-- name: EnsureApplicantRole :exec
INSERT INTO ats.user_roles (user_id, role)
VALUES ($1, 'applicant')
ON CONFLICT (user_id, role) DO NOTHING
`

func (q *Queries) EnsureApplicantRole(ctx context.Context, userID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, ensureApplicantRole, userID)
	return err
}

const getUserIDByClerkUserID = `-- name: GetUserIDByClerkUserID :one
SELECT id
FROM ats.users
WHERE clerk_user_id = $1
`

func (q *Queries) GetUserIDByClerkUserID(ctx context.Context, clerkUserID string) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, getUserIDByClerkUserID, clerkUserID)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}

const grantScannerRole = `-- name: GrantScannerRole :one
WITH inserted AS (
    INSERT INTO ats.user_roles (user_id, role, created_by)
    VALUES ($1, 'scanner', $2)
    ON CONFLICT (user_id, role) DO NOTHING
    RETURNING user_id
)
SELECT EXISTS (SELECT 1 FROM inserted) AS changed
`

type GrantScannerRoleParams struct {
	UserID    pgtype.UUID `json:"user_id"`
	CreatedBy pgtype.UUID `json:"created_by"`
}

func (q *Queries) GrantScannerRole(ctx context.Context, arg GrantScannerRoleParams) (bool, error) {
	row := q.db.QueryRow(ctx, grantScannerRole, arg.UserID, arg.CreatedBy)
	var changed bool
	err := row.Scan(&changed)
	return changed, err
}

const identityUserExists = `-- name: IdentityUserExists :one
SELECT EXISTS (
    SELECT 1 FROM ats.users WHERE id = $1
) AS user_exists
`

func (q *Queries) IdentityUserExists(ctx context.Context, id pgtype.UUID) (bool, error) {
	row := q.db.QueryRow(ctx, identityUserExists, id)
	var user_exists bool
	err := row.Scan(&user_exists)
	return user_exists, err
}

const insertBootstrapOrganizerAuditEvent = `-- name: InsertBootstrapOrganizerAuditEvent :exec
INSERT INTO ats.audit_events (event_type, subject_type, subject_id, metadata_json)
VALUES ('organizer_bootstrapped', 'user', $1, '{}'::jsonb)
`

func (q *Queries) InsertBootstrapOrganizerAuditEvent(ctx context.Context, subjectID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, insertBootstrapOrganizerAuditEvent, subjectID)
	return err
}

const insertScannerRoleAudit = `-- name: InsertScannerRoleAudit :exec
INSERT INTO ats.audit_events (actor_user_id, event_type, subject_type, subject_id, metadata_json)
VALUES (
    $1,
    $2,
    'user',
    $3,
    jsonb_build_object('role', 'scanner')
)
`

type InsertScannerRoleAuditParams struct {
	ActorUserID pgtype.UUID `json:"actor_user_id"`
	EventType   string      `json:"event_type"`
	SubjectID   pgtype.UUID `json:"subject_id"`
}

func (q *Queries) InsertScannerRoleAudit(ctx context.Context, arg InsertScannerRoleAuditParams) error {
	_, err := q.db.Exec(ctx, insertScannerRoleAudit, arg.ActorUserID, arg.EventType, arg.SubjectID)
	return err
}

const listUserRoles = `-- name: ListUserRoles :many
SELECT role
FROM ats.user_roles
WHERE user_id = $1
ORDER BY role
`

func (q *Queries) ListUserRoles(ctx context.Context, userID pgtype.UUID) ([]string, error) {
	rows, err := q.db.Query(ctx, listUserRoles, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var role string
		if err := rows.Scan(&role); err != nil {
			return nil, err
		}
		items = append(items, role)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lookupScannerUserByEmail = `-- name: LookupScannerUserByEmail :many
SELECT u.id, u.clerk_user_id,
    EXISTS (SELECT 1 FROM ats.user_roles r WHERE r.user_id = u.id AND r.role = 'scanner') AS scanner_access,
    EXISTS (SELECT 1 FROM ats.admin_email_allowlist a WHERE a.normalized_email = lower(btrim(u.primary_email))) AS is_admin
FROM ats.users u
WHERE lower(btrim(u.primary_email)) = $1::text
ORDER BY u.id
LIMIT 2
`

type LookupScannerUserByEmailRow struct {
	ID            pgtype.UUID `json:"id"`
	ClerkUserID   string      `json:"clerk_user_id"`
	ScannerAccess bool        `json:"scanner_access"`
	IsAdmin       bool        `json:"is_admin"`
}

func (q *Queries) LookupScannerUserByEmail(ctx context.Context, email string) ([]LookupScannerUserByEmailRow, error) {
	rows, err := q.db.Query(ctx, lookupScannerUserByEmail, email)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []LookupScannerUserByEmailRow{}
	for rows.Next() {
		var i LookupScannerUserByEmailRow
		if err := rows.Scan(
			&i.ID,
			&i.ClerkUserID,
			&i.ScannerAccess,
			&i.IsAdmin,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const revokeScannerRole = `-- name: RevokeScannerRole :one
WITH removed AS (
    DELETE FROM ats.user_roles
    WHERE user_id = $1
      AND role = 'scanner'
    RETURNING user_id
)
SELECT EXISTS (SELECT 1 FROM removed) AS changed
`

func (q *Queries) RevokeScannerRole(ctx context.Context, userID pgtype.UUID) (bool, error) {
	row := q.db.QueryRow(ctx, revokeScannerRole, userID)
	var changed bool
	err := row.Scan(&changed)
	return changed, err
}

const upsertClerkUser = `-- name: UpsertClerkUser :one
INSERT INTO ats.users (clerk_user_id, primary_email, display_name)
VALUES ($1, $2, $3)
ON CONFLICT (clerk_user_id) DO UPDATE
SET primary_email = EXCLUDED.primary_email,
    display_name = EXCLUDED.display_name,
    updated_at = now()
RETURNING id, clerk_user_id, primary_email, display_name, created_at, updated_at
`

type UpsertClerkUserParams struct {
	ClerkUserID  string      `json:"clerk_user_id"`
	PrimaryEmail string      `json:"primary_email"`
	DisplayName  pgtype.Text `json:"display_name"`
}

func (q *Queries) UpsertClerkUser(ctx context.Context, arg UpsertClerkUserParams) (AtsUser, error) {
	row := q.db.QueryRow(ctx, upsertClerkUser, arg.ClerkUserID, arg.PrimaryEmail, arg.DisplayName)
	var i AtsUser
	err := row.Scan(
		&i.ID,
		&i.ClerkUserID,
		&i.PrimaryEmail,
		&i.DisplayName,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const userEmailIsAdmin = `-- name: UserEmailIsAdmin :one
SELECT EXISTS (
    SELECT 1
    FROM ats.admin_email_allowlist
    WHERE normalized_email = lower(btrim($1))
) AS is_admin
`

func (q *Queries) UserEmailIsAdmin(ctx context.Context, btrim string) (bool, error) {
	row := q.db.QueryRow(ctx, userEmailIsAdmin, btrim)
	var is_admin bool
	err := row.Scan(&is_admin)
	return is_admin, err
}

const userHasOrganizerRole = `-- name: UserHasOrganizerRole :one
SELECT EXISTS(
    SELECT 1
    FROM ats.user_roles
    WHERE user_id = $1
      AND role = 'organizer'
)
`

func (q *Queries) UserHasOrganizerRole(ctx context.Context, userID pgtype.UUID) (bool, error) {
	row := q.db.QueryRow(ctx, userHasOrganizerRole, userID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}
