// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package sqlc

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type AtsActivity struct {
	ID        pgtype.UUID        `json:"id"`
	CycleID   pgtype.UUID        `json:"cycle_id"`
	Slug      string             `json:"slug"`
	Name      string             `json:"name"`
	StartsAt  pgtype.Timestamptz `json:"starts_at"`
	EndsAt    pgtype.Timestamptz `json:"ends_at"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type AtsAdminEmailAllowlist struct {
	ID              pgtype.UUID        `json:"id"`
	NormalizedEmail string             `json:"normalized_email"`
	CreatedBy       pgtype.UUID        `json:"created_by"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
}

type AtsApplication struct {
	ID                     pgtype.UUID        `json:"id"`
	CycleID                pgtype.UUID        `json:"cycle_id"`
	FormID                 pgtype.UUID        `json:"form_id"`
	ApplicantUserID        pgtype.UUID        `json:"applicant_user_id"`
	Status                 string             `json:"status"`
	SubmittedAt            pgtype.Timestamptz `json:"submitted_at"`
	WithdrawnAt            pgtype.Timestamptz `json:"withdrawn_at"`
	CurrentDecision        pgtype.Text        `json:"current_decision"`
	CurrentDecisionID      pgtype.UUID        `json:"current_decision_id"`
	DecisionReleasedAt     pgtype.Timestamptz `json:"decision_released_at"`
	ApplicantEmailSnapshot pgtype.Text        `json:"applicant_email_snapshot"`
	LockVersion            int32              `json:"lock_version"`
	CreatedAt              pgtype.Timestamptz `json:"created_at"`
	UpdatedAt              pgtype.Timestamptz `json:"updated_at"`
}

type AtsApplicationAnswer struct {
	ApplicationID pgtype.UUID        `json:"application_id"`
	QuestionKey   string             `json:"question_key"`
	ValueJson     []byte             `json:"value_json"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
}

type AtsApplicationCycle struct {
	ID                  pgtype.UUID        `json:"id"`
	Slug                string             `json:"slug"`
	Name                string             `json:"name"`
	ApplicationsOpenAt  pgtype.Timestamptz `json:"applications_open_at"`
	ApplicationsCloseAt pgtype.Timestamptz `json:"applications_close_at"`
	Active              bool               `json:"active"`
	CreatedAt           pgtype.Timestamptz `json:"created_at"`
	UpdatedAt           pgtype.Timestamptz `json:"updated_at"`
}

type AtsApplicationForm struct {
	ID          pgtype.UUID        `json:"id"`
	CycleID     pgtype.UUID        `json:"cycle_id"`
	Version     int32              `json:"version"`
	SchemaJson  []byte             `json:"schema_json"`
	PublishedAt pgtype.Timestamptz `json:"published_at"`
	CreatedBy   pgtype.UUID        `json:"created_by"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

type AtsApplicationResume struct {
	ApplicationID    pgtype.UUID        `json:"application_id"`
	ObjectKey        string             `json:"object_key"`
	OriginalFilename string             `json:"original_filename"`
	MediaType        string             `json:"media_type"`
	ByteSize         int64              `json:"byte_size"`
	Sha256           []byte             `json:"sha256"`
	UploadedAt       pgtype.Timestamptz `json:"uploaded_at"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
}

type AtsAttendanceResponse struct {
	DecisionID  pgtype.UUID        `json:"decision_id"`
	Status      string             `json:"status"`
	LockVersion int32              `json:"lock_version"`
	RespondedBy pgtype.UUID        `json:"responded_by"`
	RespondedAt pgtype.Timestamptz `json:"responded_at"`
}

type AtsAttendee struct {
	ID            pgtype.UUID        `json:"id"`
	CycleID       pgtype.UUID        `json:"cycle_id"`
	ApplicationID pgtype.UUID        `json:"application_id"`
	UserID        pgtype.UUID        `json:"user_id"`
	DisplayName   string             `json:"display_name"`
	Email         string             `json:"email"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
}

type AtsAttendeeEntitlement struct {
	AttendeeID     pgtype.UUID        `json:"attendee_id"`
	CheckpointID   pgtype.UUID        `json:"checkpoint_id"`
	CycleID        pgtype.UUID        `json:"cycle_id"`
	Allowed        bool               `json:"allowed"`
	MaxRedemptions int32              `json:"max_redemptions"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
}

type AtsAttendeeRole struct {
	AttendeeID pgtype.UUID        `json:"attendee_id"`
	Role       string             `json:"role"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
}

type AtsAuditEvent struct {
	ID           pgtype.UUID        `json:"id"`
	ActorUserID  pgtype.UUID        `json:"actor_user_id"`
	EventType    string             `json:"event_type"`
	SubjectType  string             `json:"subject_type"`
	SubjectID    pgtype.UUID        `json:"subject_id"`
	MetadataJson []byte             `json:"metadata_json"`
	RequestID    pgtype.Text        `json:"request_id"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
}

type AtsCheckpoint struct {
	ID                    pgtype.UUID        `json:"id"`
	CycleID               pgtype.UUID        `json:"cycle_id"`
	ActivityID            pgtype.UUID        `json:"activity_id"`
	Slug                  string             `json:"slug"`
	Name                  string             `json:"name"`
	OpensAt               pgtype.Timestamptz `json:"opens_at"`
	ClosesAt              pgtype.Timestamptz `json:"closes_at"`
	DefaultAllowed        bool               `json:"default_allowed"`
	DefaultMaxRedemptions int32              `json:"default_max_redemptions"`
	Active                bool               `json:"active"`
	CreatedAt             pgtype.Timestamptz `json:"created_at"`
	UpdatedAt             pgtype.Timestamptz `json:"updated_at"`
}

type AtsDecision struct {
	ID             pgtype.UUID        `json:"id"`
	ApplicationID  pgtype.UUID        `json:"application_id"`
	Outcome        string             `json:"outcome"`
	InternalReason pgtype.Text        `json:"internal_reason"`
	DecidedBy      pgtype.UUID        `json:"decided_by"`
	DecidedAt      pgtype.Timestamptz `json:"decided_at"`
	ReleasedBy     pgtype.UUID        `json:"released_by"`
	ReleasedAt     pgtype.Timestamptz `json:"released_at"`
	SupersedesID   pgtype.UUID        `json:"supersedes_id"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
}

type AtsEmailOutbox struct {
	ID                pgtype.UUID        `json:"id"`
	EventType         string             `json:"event_type"`
	RecipientUserID   pgtype.UUID        `json:"recipient_user_id"`
	RecipientEmail    string             `json:"recipient_email"`
	TemplateKey       string             `json:"template_key"`
	TemplateDataJson  []byte             `json:"template_data_json"`
	DedupeKey         string             `json:"dedupe_key"`
	Status            string             `json:"status"`
	AttemptCount      int32              `json:"attempt_count"`
	AvailableAt       pgtype.Timestamptz `json:"available_at"`
	ProviderMessageID pgtype.Text        `json:"provider_message_id"`
	LastErrorCode     pgtype.Text        `json:"last_error_code"`
	SentAt            pgtype.Timestamptz `json:"sent_at"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
}

type AtsPass struct {
	ID               pgtype.UUID        `json:"id"`
	AttendeeID       pgtype.UUID        `json:"attendee_id"`
	QrTokenHash      []byte             `json:"qr_token_hash"`
	ClaimTokenHash   []byte             `json:"claim_token_hash"`
	Status           string             `json:"status"`
	IssuedAt         pgtype.Timestamptz `json:"issued_at"`
	RevokedAt        pgtype.Timestamptz `json:"revoked_at"`
	ReplacedByPassID pgtype.UUID        `json:"replaced_by_pass_id"`
}

type AtsRedemption struct {
	ID             pgtype.UUID        `json:"id"`
	PassID         pgtype.UUID        `json:"pass_id"`
	AttendeeID     pgtype.UUID        `json:"attendee_id"`
	CheckpointID   pgtype.UUID        `json:"checkpoint_id"`
	CycleID        pgtype.UUID        `json:"cycle_id"`
	Ordinal        int32              `json:"ordinal"`
	ScannerUserID  pgtype.UUID        `json:"scanner_user_id"`
	IdempotencyKey pgtype.UUID        `json:"idempotency_key"`
	RedeemedAt     pgtype.Timestamptz `json:"redeemed_at"`
}

type AtsRedemptionRequest struct {
	ID                  pgtype.UUID        `json:"id"`
	IdempotencyKey      pgtype.UUID        `json:"idempotency_key"`
	ScannerUserID       pgtype.UUID        `json:"scanner_user_id"`
	CheckpointID        pgtype.UUID        `json:"checkpoint_id"`
	QrTokenHash         []byte             `json:"qr_token_hash"`
	PassID              pgtype.UUID        `json:"pass_id"`
	AttendeeID          pgtype.UUID        `json:"attendee_id"`
	Outcome             string             `json:"outcome"`
	AttendeeDisplayName pgtype.Text        `json:"attendee_display_name"`
	PassStatus          pgtype.Text        `json:"pass_status"`
	CheckpointName      string             `json:"checkpoint_name"`
	RedemptionID        pgtype.UUID        `json:"redemption_id"`
	CreatedAt           pgtype.Timestamptz `json:"created_at"`
}

type AtsReview struct {
	ID             pgtype.UUID        `json:"id"`
	ApplicationID  pgtype.UUID        `json:"application_id"`
	ReviewerUserID pgtype.UUID        `json:"reviewer_user_id"`
	Status         string             `json:"status"`
	ScoreJson      []byte             `json:"score_json"`
	Recommendation pgtype.Text        `json:"recommendation"`
	InternalNotes  pgtype.Text        `json:"internal_notes"`
	SubmittedAt    pgtype.Timestamptz `json:"submitted_at"`
	LockVersion    int32              `json:"lock_version"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
}

type AtsReviewAssignment struct {
	ApplicationID  pgtype.UUID        `json:"application_id"`
	ReviewerUserID pgtype.UUID        `json:"reviewer_user_id"`
	AssignedBy     pgtype.UUID        `json:"assigned_by"`
	AssignedAt     pgtype.Timestamptz `json:"assigned_at"`
}

type AtsUser struct {
	ID           pgtype.UUID        `json:"id"`
	ClerkUserID  string             `json:"clerk_user_id"`
	PrimaryEmail string             `json:"primary_email"`
	DisplayName  pgtype.Text        `json:"display_name"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}

type AtsUserRole struct {
	UserID    pgtype.UUID        `json:"user_id"`
	Role      string             `json:"role"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	CreatedBy pgtype.UUID        `json:"created_by"`
}
