// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: passes.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getActivePassForAttendeeForUpdate = `-- name: GetActivePassForAttendeeForUpdate :one
SELECT
    pass.id,
    pass.attendee_id,
    pass.qr_token_hash,
    pass.claim_token_hash,
    pass.status,
    pass.issued_at,
    pass.revoked_at,
    pass.replaced_by_pass_id
FROM ats.passes AS pass
WHERE pass.attendee_id = $1
  AND pass.status = 'active'
FOR UPDATE OF pass
`

func (q *Queries) GetActivePassForAttendeeForUpdate(ctx context.Context, attendeeID pgtype.UUID) (AtsPass, error) {
	row := q.db.QueryRow(ctx, getActivePassForAttendeeForUpdate, attendeeID)
	var i AtsPass
	err := row.Scan(
		&i.ID,
		&i.AttendeeID,
		&i.QrTokenHash,
		&i.ClaimTokenHash,
		&i.Status,
		&i.IssuedAt,
		&i.RevokedAt,
		&i.ReplacedByPassID,
	)
	return i, err
}

const getOrganizerPassSummary = `-- name: GetOrganizerPassSummary :one
SELECT
    attendee.id AS attendee_id,
    pass.id AS pass_id,
    attendee.display_name,
    pass.status,
    pass.issued_at,
    pass.revoked_at
FROM ats.attendees AS attendee
LEFT JOIN ats.passes AS pass ON pass.attendee_id = attendee.id AND pass.status = 'active'
WHERE attendee.application_id = $1
`

type GetOrganizerPassSummaryRow struct {
	AttendeeID  pgtype.UUID        `json:"attendee_id"`
	PassID      pgtype.UUID        `json:"pass_id"`
	DisplayName string             `json:"display_name"`
	Status      pgtype.Text        `json:"status"`
	IssuedAt    pgtype.Timestamptz `json:"issued_at"`
	RevokedAt   pgtype.Timestamptz `json:"revoked_at"`
}

func (q *Queries) GetOrganizerPassSummary(ctx context.Context, applicationID pgtype.UUID) (GetOrganizerPassSummaryRow, error) {
	row := q.db.QueryRow(ctx, getOrganizerPassSummary, applicationID)
	var i GetOrganizerPassSummaryRow
	err := row.Scan(
		&i.AttendeeID,
		&i.PassID,
		&i.DisplayName,
		&i.Status,
		&i.IssuedAt,
		&i.RevokedAt,
	)
	return i, err
}

const getPassAttendee = `-- name: GetPassAttendee :one
SELECT pass.attendee_id
FROM ats.passes AS pass
WHERE pass.id = $1
`

func (q *Queries) GetPassAttendee(ctx context.Context, passID pgtype.UUID) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, getPassAttendee, passID)
	var attendee_id pgtype.UUID
	err := row.Scan(&attendee_id)
	return attendee_id, err
}

const getWebPassForAttendee = `-- name: GetWebPassForAttendee :one
SELECT
    pass.id,
    pass.attendee_id,
    attendee.display_name,
    pass.status,
    pass.issued_at,
    pass.revoked_at
FROM ats.passes AS pass
JOIN ats.attendees AS attendee ON attendee.id = pass.attendee_id
JOIN ats.applications AS application ON application.id = attendee.application_id
WHERE attendee.user_id = $1
  AND pass.status = 'active'
  AND application.status = 'accepted'
  AND application.decision_released_at IS NOT NULL
`

type GetWebPassForAttendeeRow struct {
	ID          pgtype.UUID        `json:"id"`
	AttendeeID  pgtype.UUID        `json:"attendee_id"`
	DisplayName string             `json:"display_name"`
	Status      string             `json:"status"`
	IssuedAt    pgtype.Timestamptz `json:"issued_at"`
	RevokedAt   pgtype.Timestamptz `json:"revoked_at"`
}

func (q *Queries) GetWebPassForAttendee(ctx context.Context, userID pgtype.UUID) (GetWebPassForAttendeeRow, error) {
	row := q.db.QueryRow(ctx, getWebPassForAttendee, userID)
	var i GetWebPassForAttendeeRow
	err := row.Scan(
		&i.ID,
		&i.AttendeeID,
		&i.DisplayName,
		&i.Status,
		&i.IssuedAt,
		&i.RevokedAt,
	)
	return i, err
}

const insertPass = `-- name: InsertPass :one
INSERT INTO ats.passes AS pass (
    attendee_id,
    qr_token_hash,
    claim_token_hash
)
VALUES (
    $1,
    $2,
    $3
)
RETURNING
    id,
    attendee_id,
    qr_token_hash,
    claim_token_hash,
    status,
    issued_at,
    revoked_at,
    replaced_by_pass_id
`

type InsertPassParams struct {
	AttendeeID     pgtype.UUID `json:"attendee_id"`
	QrTokenHash    []byte      `json:"qr_token_hash"`
	ClaimTokenHash []byte      `json:"claim_token_hash"`
}

func (q *Queries) InsertPass(ctx context.Context, arg InsertPassParams) (AtsPass, error) {
	row := q.db.QueryRow(ctx, insertPass, arg.AttendeeID, arg.QrTokenHash, arg.ClaimTokenHash)
	var i AtsPass
	err := row.Scan(
		&i.ID,
		&i.AttendeeID,
		&i.QrTokenHash,
		&i.ClaimTokenHash,
		&i.Status,
		&i.IssuedAt,
		&i.RevokedAt,
		&i.ReplacedByPassID,
	)
	return i, err
}

const insertPassIssuedAudit = `-- name: InsertPassIssuedAudit :exec
INSERT INTO ats.audit_events AS audit_event (actor_user_id, event_type, subject_type, subject_id, metadata_json)
VALUES (
    $1,
    'pass_issued',
    'pass',
    $2,
    jsonb_build_object('attendeeId', $3::text)
)
`

type InsertPassIssuedAuditParams struct {
	ActorUserID pgtype.UUID `json:"actor_user_id"`
	PassID      pgtype.UUID `json:"pass_id"`
	AttendeeID  string      `json:"attendee_id"`
}

func (q *Queries) InsertPassIssuedAudit(ctx context.Context, arg InsertPassIssuedAuditParams) error {
	_, err := q.db.Exec(ctx, insertPassIssuedAudit, arg.ActorUserID, arg.PassID, arg.AttendeeID)
	return err
}

const insertPassLinkEmail = `-- name: InsertPassLinkEmail :exec
INSERT INTO ats.email_outbox AS outbox (
    event_type,
    recipient_user_id,
    recipient_email,
    template_key,
    template_data_json,
    dedupe_key
)
VALUES (
    'pass_link',
    $1,
    $2,
    'pass_link',
    $3,
    $4
)
ON CONFLICT (dedupe_key) DO NOTHING
`

type InsertPassLinkEmailParams struct {
	RecipientUserID  pgtype.UUID `json:"recipient_user_id"`
	RecipientEmail   string      `json:"recipient_email"`
	TemplateDataJson []byte      `json:"template_data_json"`
	DedupeKey        string      `json:"dedupe_key"`
}

func (q *Queries) InsertPassLinkEmail(ctx context.Context, arg InsertPassLinkEmailParams) error {
	_, err := q.db.Exec(ctx, insertPassLinkEmail,
		arg.RecipientUserID,
		arg.RecipientEmail,
		arg.TemplateDataJson,
		arg.DedupeKey,
	)
	return err
}

const insertPassReissuedAudit = `-- name: InsertPassReissuedAudit :exec
INSERT INTO ats.audit_events AS audit_event (actor_user_id, event_type, subject_type, subject_id, metadata_json)
VALUES (
    $1,
    'pass_reissued',
    'pass',
    $2,
    jsonb_build_object(
        'attendeeId',
        $3::text,
        'replacementPassId',
        $4::text
    )
)
`

type InsertPassReissuedAuditParams struct {
	ActorUserID       pgtype.UUID `json:"actor_user_id"`
	PassID            pgtype.UUID `json:"pass_id"`
	AttendeeID        string      `json:"attendee_id"`
	ReplacementPassID string      `json:"replacement_pass_id"`
}

func (q *Queries) InsertPassReissuedAudit(ctx context.Context, arg InsertPassReissuedAuditParams) error {
	_, err := q.db.Exec(ctx, insertPassReissuedAudit,
		arg.ActorUserID,
		arg.PassID,
		arg.AttendeeID,
		arg.ReplacementPassID,
	)
	return err
}

const insertPassRevokedAudit = `-- name: InsertPassRevokedAudit :exec
INSERT INTO ats.audit_events AS audit_event (actor_user_id, event_type, subject_type, subject_id, metadata_json)
VALUES (
    $1,
    'pass_revoked',
    'pass',
    $2,
    jsonb_build_object('attendeeId', $3::text)
)
`

type InsertPassRevokedAuditParams struct {
	ActorUserID pgtype.UUID `json:"actor_user_id"`
	PassID      pgtype.UUID `json:"pass_id"`
	AttendeeID  string      `json:"attendee_id"`
}

func (q *Queries) InsertPassRevokedAudit(ctx context.Context, arg InsertPassRevokedAuditParams) error {
	_, err := q.db.Exec(ctx, insertPassRevokedAudit, arg.ActorUserID, arg.PassID, arg.AttendeeID)
	return err
}

const lockAcceptedAttendeeForIssue = `-- name: LockAcceptedAttendeeForIssue :one
SELECT
    attendee.id,
    attendee.user_id,
    attendee.display_name,
    attendee.email
FROM ats.attendees AS attendee
JOIN ats.applications AS application ON application.id = attendee.application_id
WHERE attendee.id = $1
  AND application.status = 'accepted'
  AND application.decision_released_at IS NOT NULL
FOR UPDATE OF attendee, application
`

type LockAcceptedAttendeeForIssueRow struct {
	ID          pgtype.UUID `json:"id"`
	UserID      pgtype.UUID `json:"user_id"`
	DisplayName string      `json:"display_name"`
	Email       string      `json:"email"`
}

func (q *Queries) LockAcceptedAttendeeForIssue(ctx context.Context, attendeeID pgtype.UUID) (LockAcceptedAttendeeForIssueRow, error) {
	row := q.db.QueryRow(ctx, lockAcceptedAttendeeForIssue, attendeeID)
	var i LockAcceptedAttendeeForIssueRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.DisplayName,
		&i.Email,
	)
	return i, err
}

const lockActivePassForMutation = `-- name: LockActivePassForMutation :one
SELECT
    pass.id,
    pass.attendee_id,
    pass.qr_token_hash,
    pass.claim_token_hash,
    pass.status,
    pass.issued_at,
    pass.revoked_at,
    pass.replaced_by_pass_id,
    attendee.user_id,
    attendee.display_name,
    attendee.email
FROM ats.passes AS pass
JOIN ats.attendees AS attendee ON attendee.id = pass.attendee_id
JOIN ats.applications AS application ON application.id = attendee.application_id
WHERE pass.id = $1
  AND pass.status = 'active'
  AND application.status = 'accepted'
  AND application.decision_released_at IS NOT NULL
FOR UPDATE OF pass, attendee, application
`

type LockActivePassForMutationRow struct {
	ID               pgtype.UUID        `json:"id"`
	AttendeeID       pgtype.UUID        `json:"attendee_id"`
	QrTokenHash      []byte             `json:"qr_token_hash"`
	ClaimTokenHash   []byte             `json:"claim_token_hash"`
	Status           string             `json:"status"`
	IssuedAt         pgtype.Timestamptz `json:"issued_at"`
	RevokedAt        pgtype.Timestamptz `json:"revoked_at"`
	ReplacedByPassID pgtype.UUID        `json:"replaced_by_pass_id"`
	UserID           pgtype.UUID        `json:"user_id"`
	DisplayName      string             `json:"display_name"`
	Email            string             `json:"email"`
}

func (q *Queries) LockActivePassForMutation(ctx context.Context, passID pgtype.UUID) (LockActivePassForMutationRow, error) {
	row := q.db.QueryRow(ctx, lockActivePassForMutation, passID)
	var i LockActivePassForMutationRow
	err := row.Scan(
		&i.ID,
		&i.AttendeeID,
		&i.QrTokenHash,
		&i.ClaimTokenHash,
		&i.Status,
		&i.IssuedAt,
		&i.RevokedAt,
		&i.ReplacedByPassID,
		&i.UserID,
		&i.DisplayName,
		&i.Email,
	)
	return i, err
}

const replaceActivePass = `-- name: ReplaceActivePass :exec
UPDATE ats.passes AS pass
SET status = 'replaced',
    revoked_at = CURRENT_TIMESTAMP,
    replaced_by_pass_id = $1
WHERE pass.id = $2
  AND pass.status = 'active'
`

type ReplaceActivePassParams struct {
	ReplacementPassID pgtype.UUID `json:"replacement_pass_id"`
	PassID            pgtype.UUID `json:"pass_id"`
}

func (q *Queries) ReplaceActivePass(ctx context.Context, arg ReplaceActivePassParams) error {
	_, err := q.db.Exec(ctx, replaceActivePass, arg.ReplacementPassID, arg.PassID)
	return err
}

const resolveActivePassByClaimTokenHash = `-- name: ResolveActivePassByClaimTokenHash :one
SELECT
    pass.id,
    pass.attendee_id,
    attendee.display_name,
    pass.status,
    pass.issued_at
FROM ats.passes AS pass
JOIN ats.attendees AS attendee ON attendee.id = pass.attendee_id
JOIN ats.applications AS application ON application.id = attendee.application_id
WHERE pass.claim_token_hash = $1
  AND pass.status = 'active'
  AND application.status = 'accepted'
  AND application.decision_released_at IS NOT NULL
`

type ResolveActivePassByClaimTokenHashRow struct {
	ID          pgtype.UUID        `json:"id"`
	AttendeeID  pgtype.UUID        `json:"attendee_id"`
	DisplayName string             `json:"display_name"`
	Status      string             `json:"status"`
	IssuedAt    pgtype.Timestamptz `json:"issued_at"`
}

func (q *Queries) ResolveActivePassByClaimTokenHash(ctx context.Context, claimTokenHash []byte) (ResolveActivePassByClaimTokenHashRow, error) {
	row := q.db.QueryRow(ctx, resolveActivePassByClaimTokenHash, claimTokenHash)
	var i ResolveActivePassByClaimTokenHashRow
	err := row.Scan(
		&i.ID,
		&i.AttendeeID,
		&i.DisplayName,
		&i.Status,
		&i.IssuedAt,
	)
	return i, err
}

const revokeActivePass = `-- name: RevokeActivePass :exec
UPDATE ats.passes AS pass
SET status = 'revoked',
    revoked_at = CURRENT_TIMESTAMP
WHERE pass.id = $1
  AND pass.status = 'active'
`

func (q *Queries) RevokeActivePass(ctx context.Context, passID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, revokeActivePass, passID)
	return err
}
