// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	AcquireOrganizerBootstrapLock(ctx context.Context) error
	ApplicationHasResume(ctx context.Context, applicationID pgtype.UUID) (bool, error)
	AssignReviewer(ctx context.Context, arg AssignReviewerParams) (bool, error)
	AssignUserRole(ctx context.Context, arg AssignUserRoleParams) error
	CountCommittedRedemptions(ctx context.Context, arg CountCommittedRedemptionsParams) (int64, error)
	CountOrganizerRoles(ctx context.Context) (int64, error)
	CreateApplication(ctx context.Context, arg CreateApplicationParams) (pgtype.UUID, error)
	DeleteApplicationAnswers(ctx context.Context, applicationID pgtype.UUID) error
	EnsureApplicantRole(ctx context.Context, userID pgtype.UUID) error
	EnsureIntakeFixtureCycle(ctx context.Context, arg EnsureIntakeFixtureCycleParams) error
	EnsureIntakeFixtureForm(ctx context.Context, arg EnsureIntakeFixtureFormParams) error
	FindRedemptionRequestForUpdate(ctx context.Context, idempotencyKey pgtype.UUID) (AtsRedemptionRequest, error)
	GetActivePassForAttendeeForUpdate(ctx context.Context, attendeeID pgtype.UUID) (AtsPass, error)
	GetApplicationForApplicant(ctx context.Context, arg GetApplicationForApplicantParams) (GetApplicationForApplicantRow, error)
	GetApplicationResumeForAdmin(ctx context.Context, applicationID pgtype.UUID) (AtsApplicationResume, error)
	GetApplicationResumeForApplicant(ctx context.Context, arg GetApplicationResumeForApplicantParams) (AtsApplicationResume, error)
	GetAttendeeEntitlementForRedemption(ctx context.Context, arg GetAttendeeEntitlementForRedemptionParams) (GetAttendeeEntitlementForRedemptionRow, error)
	GetCurrentApplicationForm(ctx context.Context) (GetCurrentApplicationFormRow, error)
	GetDraftApplicationResumeTarget(ctx context.Context, arg GetDraftApplicationResumeTargetParams) (pgtype.UUID, error)
	GetLatestDecisionForApplication(ctx context.Context, id pgtype.UUID) (AtsDecision, error)
	GetOrganizerApplication(ctx context.Context, id pgtype.UUID) (GetOrganizerApplicationRow, error)
	GetOrganizerPassSummary(ctx context.Context, applicationID pgtype.UUID) (GetOrganizerPassSummaryRow, error)
	GetPassAttendee(ctx context.Context, passID pgtype.UUID) (pgtype.UUID, error)
	GetReleasedDecisionForApplicant(ctx context.Context, arg GetReleasedDecisionForApplicantParams) (GetReleasedDecisionForApplicantRow, error)
	GetReviewerApplication(ctx context.Context, arg GetReviewerApplicationParams) (GetReviewerApplicationRow, error)
	GetUserIDByClerkUserID(ctx context.Context, clerkUserID string) (pgtype.UUID, error)
	GetWebPassForAttendee(ctx context.Context, userID pgtype.UUID) (GetWebPassForAttendeeRow, error)
	GrantReviewerRole(ctx context.Context, arg GrantReviewerRoleParams) (bool, error)
	GrantScannerRole(ctx context.Context, arg GrantScannerRoleParams) (bool, error)
	IdentityUserExists(ctx context.Context, id pgtype.UUID) (bool, error)
	InsertAttendeeCreatedAudit(ctx context.Context, arg InsertAttendeeCreatedAuditParams) error
	InsertBootstrapOrganizerAuditEvent(ctx context.Context, subjectID pgtype.UUID) error
	InsertDecision(ctx context.Context, arg InsertDecisionParams) (AtsDecision, error)
	InsertDecisionRecordedAudit(ctx context.Context, arg InsertDecisionRecordedAuditParams) error
	InsertDecisionReleaseEmail(ctx context.Context, arg InsertDecisionReleaseEmailParams) error
	InsertDecisionReleasedAudit(ctx context.Context, arg InsertDecisionReleasedAuditParams) error
	InsertPass(ctx context.Context, arg InsertPassParams) (AtsPass, error)
	InsertPassIssuedAudit(ctx context.Context, arg InsertPassIssuedAuditParams) error
	InsertPassLinkEmail(ctx context.Context, arg InsertPassLinkEmailParams) error
	InsertPassReissuedAudit(ctx context.Context, arg InsertPassReissuedAuditParams) error
	InsertPassRevokedAudit(ctx context.Context, arg InsertPassRevokedAuditParams) error
	InsertRedemption(ctx context.Context, arg InsertRedemptionParams) error
	InsertRedemptionAudit(ctx context.Context, arg InsertRedemptionAuditParams) error
	InsertRedemptionRequest(ctx context.Context, arg InsertRedemptionRequestParams) error
	InsertReviewAssignmentAudit(ctx context.Context, arg InsertReviewAssignmentAuditParams) error
	InsertReviewSubmissionAudit(ctx context.Context, arg InsertReviewSubmissionAuditParams) error
	InsertReviewerRoleAudit(ctx context.Context, arg InsertReviewerRoleAuditParams) error
	InsertScannerRoleAudit(ctx context.Context, arg InsertScannerRoleAuditParams) error
	InsertSubmissionConfirmation(ctx context.Context, arg InsertSubmissionConfirmationParams) error
	IsApplicationSubmissionWindowOpen(ctx context.Context, arg IsApplicationSubmissionWindowOpenParams) (bool, error)
	ListActiveCheckpoints(ctx context.Context) ([]ListActiveCheckpointsRow, error)
	ListApplicationsForApplicant(ctx context.Context, applicantUserID pgtype.UUID) ([]ListApplicationsForApplicantRow, error)
	ListOrganizerApplications(ctx context.Context, arg ListOrganizerApplicationsParams) ([]ListOrganizerApplicationsRow, error)
	ListReviewerApplications(ctx context.Context, reviewerUserID pgtype.UUID) ([]ListReviewerApplicationsRow, error)
	ListUserRoles(ctx context.Context, userID pgtype.UUID) ([]string, error)
	LockAcceptedAttendeeForIssue(ctx context.Context, attendeeID pgtype.UUID) (LockAcceptedAttendeeForIssueRow, error)
	LockActivePassForMutation(ctx context.Context, passID pgtype.UUID) (LockActivePassForMutationRow, error)
	LockApplicationForDecision(ctx context.Context, id pgtype.UUID) (LockApplicationForDecisionRow, error)
	LockCheckpointForRedemption(ctx context.Context, checkpointID pgtype.UUID) (LockCheckpointForRedemptionRow, error)
	LockCurrentDecisionForRelease(ctx context.Context, id pgtype.UUID) (LockCurrentDecisionForReleaseRow, error)
	LockPassForRedemptionByQRTokenHash(ctx context.Context, qrTokenHash []byte) (LockPassForRedemptionByQRTokenHashRow, error)
	LookupScannerUserByEmail(ctx context.Context, email string) ([]LookupScannerUserByEmailRow, error)
	OtherActiveApplicationCycleExists(ctx context.Context, id pgtype.UUID) (bool, error)
	ReleaseDecision(ctx context.Context, arg ReleaseDecisionParams) (pgtype.Timestamptz, error)
	ReplaceActivePass(ctx context.Context, arg ReplaceActivePassParams) error
	ReplaceApplicationAnswers(ctx context.Context, arg ReplaceApplicationAnswersParams) error
	ResolveActivePassByClaimTokenHash(ctx context.Context, claimTokenHash []byte) (ResolveActivePassByClaimTokenHashRow, error)
	ResolveActivePassByQRTokenHash(ctx context.Context, qrTokenHash []byte) (ResolveActivePassByQRTokenHashRow, error)
	RevokeActivePass(ctx context.Context, passID pgtype.UUID) error
	RevokeScannerRole(ctx context.Context, userID pgtype.UUID) (bool, error)
	SeedAttendeeHackerRole(ctx context.Context, attendeeID pgtype.UUID) error
	SeedIntakeFixtureUser(ctx context.Context, arg SeedIntakeFixtureUserParams) (pgtype.UUID, error)
	SubmitReview(ctx context.Context, arg SubmitReviewParams) (pgtype.UUID, error)
	UpdateApplicationDecisionCache(ctx context.Context, arg UpdateApplicationDecisionCacheParams) error
	UpdateApplicationDecisionRelease(ctx context.Context, arg UpdateApplicationDecisionReleaseParams) error
	UpdateApplicationDraft(ctx context.Context, arg UpdateApplicationDraftParams) (pgtype.UUID, error)
	UpdateApplicationSubmission(ctx context.Context, arg UpdateApplicationSubmissionParams) (pgtype.UUID, error)
	UpdateReviewDraft(ctx context.Context, arg UpdateReviewDraftParams) (pgtype.UUID, error)
	UpsertAcceptedAttendee(ctx context.Context, arg UpsertAcceptedAttendeeParams) (UpsertAcceptedAttendeeRow, error)
	UpsertApplicationResume(ctx context.Context, arg UpsertApplicationResumeParams) (AtsApplicationResume, error)
	UpsertClerkUser(ctx context.Context, arg UpsertClerkUserParams) (AtsUser, error)
	UserEmailIsAdmin(ctx context.Context, btrim string) (bool, error)
	UserExists(ctx context.Context, id pgtype.UUID) (bool, error)
	UserHasOrganizerRole(ctx context.Context, userID pgtype.UUID) (bool, error)
	UserHasReviewerRole(ctx context.Context, userID pgtype.UUID) (bool, error)
}

var _ Querier = (*Queries)(nil)
