// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: redemptions.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countCommittedRedemptions = `-- name: CountCommittedRedemptions :one
SELECT count(*)
FROM ats.redemptions AS redemption
WHERE redemption.attendee_id = $1
  AND redemption.checkpoint_id = $2
`

type CountCommittedRedemptionsParams struct {
	AttendeeID   pgtype.UUID `json:"attendee_id"`
	CheckpointID pgtype.UUID `json:"checkpoint_id"`
}

func (q *Queries) CountCommittedRedemptions(ctx context.Context, arg CountCommittedRedemptionsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countCommittedRedemptions, arg.AttendeeID, arg.CheckpointID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const findRedemptionRequestForUpdate = `-- name: FindRedemptionRequestForUpdate :one
SELECT
    request.id,
    request.idempotency_key,
    request.scanner_user_id,
    request.checkpoint_id,
    request.qr_token_hash,
    request.pass_id,
    request.attendee_id,
    request.outcome,
    request.attendee_display_name,
    request.pass_status,
    request.checkpoint_name,
    request.redemption_id,
    request.created_at
FROM ats.redemption_requests AS request
WHERE request.idempotency_key = $1
FOR UPDATE OF request
`

func (q *Queries) FindRedemptionRequestForUpdate(ctx context.Context, idempotencyKey pgtype.UUID) (AtsRedemptionRequest, error) {
	row := q.db.QueryRow(ctx, findRedemptionRequestForUpdate, idempotencyKey)
	var i AtsRedemptionRequest
	err := row.Scan(
		&i.ID,
		&i.IdempotencyKey,
		&i.ScannerUserID,
		&i.CheckpointID,
		&i.QrTokenHash,
		&i.PassID,
		&i.AttendeeID,
		&i.Outcome,
		&i.AttendeeDisplayName,
		&i.PassStatus,
		&i.CheckpointName,
		&i.RedemptionID,
		&i.CreatedAt,
	)
	return i, err
}

const getAttendeeEntitlementForRedemption = `-- name: GetAttendeeEntitlementForRedemption :one
SELECT entitlement.allowed, entitlement.max_redemptions
FROM ats.attendee_entitlements AS entitlement
WHERE entitlement.attendee_id = $1
  AND entitlement.checkpoint_id = $2
  AND entitlement.cycle_id = $3
FOR UPDATE OF entitlement
`

type GetAttendeeEntitlementForRedemptionParams struct {
	AttendeeID   pgtype.UUID `json:"attendee_id"`
	CheckpointID pgtype.UUID `json:"checkpoint_id"`
	CycleID      pgtype.UUID `json:"cycle_id"`
}

type GetAttendeeEntitlementForRedemptionRow struct {
	Allowed        bool  `json:"allowed"`
	MaxRedemptions int32 `json:"max_redemptions"`
}

func (q *Queries) GetAttendeeEntitlementForRedemption(ctx context.Context, arg GetAttendeeEntitlementForRedemptionParams) (GetAttendeeEntitlementForRedemptionRow, error) {
	row := q.db.QueryRow(ctx, getAttendeeEntitlementForRedemption, arg.AttendeeID, arg.CheckpointID, arg.CycleID)
	var i GetAttendeeEntitlementForRedemptionRow
	err := row.Scan(&i.Allowed, &i.MaxRedemptions)
	return i, err
}

const insertRedemption = `-- name: InsertRedemption :exec
INSERT INTO ats.redemptions (
    id,
    pass_id,
    attendee_id,
    checkpoint_id,
    cycle_id,
    ordinal,
    scanner_user_id,
    idempotency_key
)
VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7,
    $8
)
`

type InsertRedemptionParams struct {
	ID             pgtype.UUID `json:"id"`
	PassID         pgtype.UUID `json:"pass_id"`
	AttendeeID     pgtype.UUID `json:"attendee_id"`
	CheckpointID   pgtype.UUID `json:"checkpoint_id"`
	CycleID        pgtype.UUID `json:"cycle_id"`
	Ordinal        int32       `json:"ordinal"`
	ScannerUserID  pgtype.UUID `json:"scanner_user_id"`
	IdempotencyKey pgtype.UUID `json:"idempotency_key"`
}

func (q *Queries) InsertRedemption(ctx context.Context, arg InsertRedemptionParams) error {
	_, err := q.db.Exec(ctx, insertRedemption,
		arg.ID,
		arg.PassID,
		arg.AttendeeID,
		arg.CheckpointID,
		arg.CycleID,
		arg.Ordinal,
		arg.ScannerUserID,
		arg.IdempotencyKey,
	)
	return err
}

const insertRedemptionAudit = `-- name: InsertRedemptionAudit :exec
INSERT INTO ats.audit_events AS audit_event (
    actor_user_id,
    event_type,
    subject_type,
    subject_id,
    metadata_json
)
VALUES (
    $1,
    'redemption_recorded',
    'redemption',
    COALESCE($2, $3),
    jsonb_build_object(
        'scannerUserId', $1::text,
        'checkpointId', $3::text,
        'attendeeId', $4::text,
        'passId', $5::text,
        'redemptionId', $2::text,
        'idempotencyKey', $6::text,
        'outcome', $7
    )
)
`

type InsertRedemptionAuditParams struct {
	ScannerUserID  pgtype.UUID `json:"scanner_user_id"`
	RedemptionID   interface{} `json:"redemption_id"`
	CheckpointID   interface{} `json:"checkpoint_id"`
	AttendeeID     pgtype.Text `json:"attendee_id"`
	PassID         pgtype.Text `json:"pass_id"`
	IdempotencyKey string      `json:"idempotency_key"`
	Outcome        interface{} `json:"outcome"`
}

func (q *Queries) InsertRedemptionAudit(ctx context.Context, arg InsertRedemptionAuditParams) error {
	_, err := q.db.Exec(ctx, insertRedemptionAudit,
		arg.ScannerUserID,
		arg.RedemptionID,
		arg.CheckpointID,
		arg.AttendeeID,
		arg.PassID,
		arg.IdempotencyKey,
		arg.Outcome,
	)
	return err
}

const insertRedemptionRequest = `-- name: InsertRedemptionRequest :exec
INSERT INTO ats.redemption_requests (
    idempotency_key,
    scanner_user_id,
    checkpoint_id,
    qr_token_hash,
    pass_id,
    attendee_id,
    outcome,
    attendee_display_name,
    pass_status,
    checkpoint_name,
    redemption_id
)
VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7,
    $8,
    $9,
    $10,
    $11
)
`

type InsertRedemptionRequestParams struct {
	IdempotencyKey      pgtype.UUID `json:"idempotency_key"`
	ScannerUserID       pgtype.UUID `json:"scanner_user_id"`
	CheckpointID        pgtype.UUID `json:"checkpoint_id"`
	QrTokenHash         []byte      `json:"qr_token_hash"`
	PassID              pgtype.UUID `json:"pass_id"`
	AttendeeID          pgtype.UUID `json:"attendee_id"`
	Outcome             string      `json:"outcome"`
	AttendeeDisplayName pgtype.Text `json:"attendee_display_name"`
	PassStatus          pgtype.Text `json:"pass_status"`
	CheckpointName      string      `json:"checkpoint_name"`
	RedemptionID        pgtype.UUID `json:"redemption_id"`
}

func (q *Queries) InsertRedemptionRequest(ctx context.Context, arg InsertRedemptionRequestParams) error {
	_, err := q.db.Exec(ctx, insertRedemptionRequest,
		arg.IdempotencyKey,
		arg.ScannerUserID,
		arg.CheckpointID,
		arg.QrTokenHash,
		arg.PassID,
		arg.AttendeeID,
		arg.Outcome,
		arg.AttendeeDisplayName,
		arg.PassStatus,
		arg.CheckpointName,
		arg.RedemptionID,
	)
	return err
}

const listActiveCheckpoints = `-- name: ListActiveCheckpoints :many
SELECT checkpoint.id, checkpoint.name
FROM ats.checkpoints AS checkpoint
WHERE checkpoint.active
ORDER BY checkpoint.name, checkpoint.id
`

type ListActiveCheckpointsRow struct {
	ID   pgtype.UUID `json:"id"`
	Name string      `json:"name"`
}

func (q *Queries) ListActiveCheckpoints(ctx context.Context) ([]ListActiveCheckpointsRow, error) {
	rows, err := q.db.Query(ctx, listActiveCheckpoints)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListActiveCheckpointsRow{}
	for rows.Next() {
		var i ListActiveCheckpointsRow
		if err := rows.Scan(&i.ID, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockCheckpointForRedemption = `-- name: LockCheckpointForRedemption :one
SELECT
    checkpoint.id,
    checkpoint.cycle_id,
    checkpoint.name,
    checkpoint.opens_at,
    checkpoint.closes_at,
    checkpoint.default_allowed,
    checkpoint.default_max_redemptions,
    checkpoint.active
FROM ats.checkpoints AS checkpoint
WHERE checkpoint.id = $1
FOR UPDATE OF checkpoint
`

type LockCheckpointForRedemptionRow struct {
	ID                    pgtype.UUID        `json:"id"`
	CycleID               pgtype.UUID        `json:"cycle_id"`
	Name                  string             `json:"name"`
	OpensAt               pgtype.Timestamptz `json:"opens_at"`
	ClosesAt              pgtype.Timestamptz `json:"closes_at"`
	DefaultAllowed        bool               `json:"default_allowed"`
	DefaultMaxRedemptions int32              `json:"default_max_redemptions"`
	Active                bool               `json:"active"`
}

func (q *Queries) LockCheckpointForRedemption(ctx context.Context, checkpointID pgtype.UUID) (LockCheckpointForRedemptionRow, error) {
	row := q.db.QueryRow(ctx, lockCheckpointForRedemption, checkpointID)
	var i LockCheckpointForRedemptionRow
	err := row.Scan(
		&i.ID,
		&i.CycleID,
		&i.Name,
		&i.OpensAt,
		&i.ClosesAt,
		&i.DefaultAllowed,
		&i.DefaultMaxRedemptions,
		&i.Active,
	)
	return i, err
}

const lockPassForRedemptionByQRTokenHash = `-- name: LockPassForRedemptionByQRTokenHash :one
SELECT
    pass.id,
    pass.attendee_id,
    attendee.cycle_id,
    attendee.display_name,
    pass.status,
    application.status = 'accepted' AND application.decision_released_at IS NOT NULL AS eligible
FROM ats.passes AS pass
JOIN ats.attendees AS attendee ON attendee.id = pass.attendee_id
JOIN ats.applications AS application ON application.id = attendee.application_id
WHERE pass.qr_token_hash = $1
FOR UPDATE OF pass, attendee, application
`

type LockPassForRedemptionByQRTokenHashRow struct {
	ID          pgtype.UUID `json:"id"`
	AttendeeID  pgtype.UUID `json:"attendee_id"`
	CycleID     pgtype.UUID `json:"cycle_id"`
	DisplayName string      `json:"display_name"`
	Status      string      `json:"status"`
	Eligible    pgtype.Bool `json:"eligible"`
}

func (q *Queries) LockPassForRedemptionByQRTokenHash(ctx context.Context, qrTokenHash []byte) (LockPassForRedemptionByQRTokenHashRow, error) {
	row := q.db.QueryRow(ctx, lockPassForRedemptionByQRTokenHash, qrTokenHash)
	var i LockPassForRedemptionByQRTokenHashRow
	err := row.Scan(
		&i.ID,
		&i.AttendeeID,
		&i.CycleID,
		&i.DisplayName,
		&i.Status,
		&i.Eligible,
	)
	return i, err
}

const resolveActivePassByQRTokenHash = `-- name: ResolveActivePassByQRTokenHash :one
SELECT
    pass.id,
    pass.attendee_id,
    attendee.display_name,
    pass.status,
    pass.issued_at
FROM ats.passes AS pass
JOIN ats.attendees AS attendee ON attendee.id = pass.attendee_id
JOIN ats.applications AS application ON application.id = attendee.application_id
WHERE pass.qr_token_hash = $1
  AND pass.status = 'active'
  AND application.status = 'accepted'
  AND application.decision_released_at IS NOT NULL
`

type ResolveActivePassByQRTokenHashRow struct {
	ID          pgtype.UUID        `json:"id"`
	AttendeeID  pgtype.UUID        `json:"attendee_id"`
	DisplayName string             `json:"display_name"`
	Status      string             `json:"status"`
	IssuedAt    pgtype.Timestamptz `json:"issued_at"`
}

func (q *Queries) ResolveActivePassByQRTokenHash(ctx context.Context, qrTokenHash []byte) (ResolveActivePassByQRTokenHashRow, error) {
	row := q.db.QueryRow(ctx, resolveActivePassByQRTokenHash, qrTokenHash)
	var i ResolveActivePassByQRTokenHashRow
	err := row.Scan(
		&i.ID,
		&i.AttendeeID,
		&i.DisplayName,
		&i.Status,
		&i.IssuedAt,
	)
	return i, err
}
