// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: resumes.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const applicationHasResume = `-- name: ApplicationHasResume :one
SELECT EXISTS (
    SELECT 1 FROM ats.application_resumes WHERE application_id = $1
) AS has_resume
`

func (q *Queries) ApplicationHasResume(ctx context.Context, applicationID pgtype.UUID) (bool, error) {
	row := q.db.QueryRow(ctx, applicationHasResume, applicationID)
	var has_resume bool
	err := row.Scan(&has_resume)
	return has_resume, err
}

const getApplicationResumeForAdmin = `-- name: GetApplicationResumeForAdmin :one
SELECT resumes.application_id, resumes.object_key, resumes.original_filename,
       resumes.media_type, resumes.byte_size, resumes.sha256,
       resumes.uploaded_at, resumes.updated_at
FROM ats.application_resumes AS resumes
JOIN ats.applications AS applications ON applications.id = resumes.application_id
WHERE resumes.application_id = $1
  AND applications.status IN ('submitted', 'accepted', 'waitlisted', 'rejected')
`

func (q *Queries) GetApplicationResumeForAdmin(ctx context.Context, applicationID pgtype.UUID) (AtsApplicationResume, error) {
	row := q.db.QueryRow(ctx, getApplicationResumeForAdmin, applicationID)
	var i AtsApplicationResume
	err := row.Scan(
		&i.ApplicationID,
		&i.ObjectKey,
		&i.OriginalFilename,
		&i.MediaType,
		&i.ByteSize,
		&i.Sha256,
		&i.UploadedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getApplicationResumeForApplicant = `-- name: GetApplicationResumeForApplicant :one
SELECT resumes.application_id, resumes.object_key, resumes.original_filename,
       resumes.media_type, resumes.byte_size, resumes.sha256,
       resumes.uploaded_at, resumes.updated_at
FROM ats.application_resumes AS resumes
JOIN ats.applications AS applications ON applications.id = resumes.application_id
WHERE resumes.application_id = $1
  AND applications.applicant_user_id = $2
`

type GetApplicationResumeForApplicantParams struct {
	ApplicationID   pgtype.UUID `json:"application_id"`
	ApplicantUserID pgtype.UUID `json:"applicant_user_id"`
}

func (q *Queries) GetApplicationResumeForApplicant(ctx context.Context, arg GetApplicationResumeForApplicantParams) (AtsApplicationResume, error) {
	row := q.db.QueryRow(ctx, getApplicationResumeForApplicant, arg.ApplicationID, arg.ApplicantUserID)
	var i AtsApplicationResume
	err := row.Scan(
		&i.ApplicationID,
		&i.ObjectKey,
		&i.OriginalFilename,
		&i.MediaType,
		&i.ByteSize,
		&i.Sha256,
		&i.UploadedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getDraftApplicationResumeTarget = `-- name: GetDraftApplicationResumeTarget :one
SELECT applications.id
FROM ats.applications
WHERE applications.id = $1
  AND applications.applicant_user_id = $2
  AND applications.status = 'draft'
`

type GetDraftApplicationResumeTargetParams struct {
	ID              pgtype.UUID `json:"id"`
	ApplicantUserID pgtype.UUID `json:"applicant_user_id"`
}

func (q *Queries) GetDraftApplicationResumeTarget(ctx context.Context, arg GetDraftApplicationResumeTargetParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, getDraftApplicationResumeTarget, arg.ID, arg.ApplicantUserID)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}

const upsertApplicationResume = `-- name: UpsertApplicationResume :one
INSERT INTO ats.application_resumes (
    application_id, object_key, original_filename, media_type, byte_size, sha256
)
VALUES ($1, $2, $3, 'application/pdf', $4, $5)
ON CONFLICT (application_id) DO UPDATE
SET object_key = EXCLUDED.object_key,
    original_filename = EXCLUDED.original_filename,
    media_type = EXCLUDED.media_type,
    byte_size = EXCLUDED.byte_size,
    sha256 = EXCLUDED.sha256,
    uploaded_at = CURRENT_TIMESTAMP,
    updated_at = CURRENT_TIMESTAMP
RETURNING application_id, object_key, original_filename, media_type,
          byte_size, sha256, uploaded_at, updated_at
`

type UpsertApplicationResumeParams struct {
	ApplicationID    pgtype.UUID `json:"application_id"`
	ObjectKey        string      `json:"object_key"`
	OriginalFilename string      `json:"original_filename"`
	ByteSize         int64       `json:"byte_size"`
	Sha256           []byte      `json:"sha256"`
}

func (q *Queries) UpsertApplicationResume(ctx context.Context, arg UpsertApplicationResumeParams) (AtsApplicationResume, error) {
	row := q.db.QueryRow(ctx, upsertApplicationResume,
		arg.ApplicationID,
		arg.ObjectKey,
		arg.OriginalFilename,
		arg.ByteSize,
		arg.Sha256,
	)
	var i AtsApplicationResume
	err := row.Scan(
		&i.ApplicationID,
		&i.ObjectKey,
		&i.OriginalFilename,
		&i.MediaType,
		&i.ByteSize,
		&i.Sha256,
		&i.UploadedAt,
		&i.UpdatedAt,
	)
	return i, err
}
