// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: reviews.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const assignReviewer = `-- name: AssignReviewer :one
WITH inserted AS (
    INSERT INTO ats.review_assignments (application_id, reviewer_user_id, assigned_by)
    SELECT applications.id, $1, $2
    FROM ats.applications AS applications
    WHERE applications.id = $3
      AND applications.status = 'submitted'
      AND EXISTS (
          SELECT 1
          FROM ats.user_roles
          WHERE user_id = $1
            AND role = 'reviewer'
      )
    ON CONFLICT (application_id, reviewer_user_id) DO NOTHING
    RETURNING application_id
)
SELECT EXISTS (SELECT 1 FROM inserted) AS assigned
`

type AssignReviewerParams struct {
	ReviewerUserID pgtype.UUID `json:"reviewer_user_id"`
	AssignedBy     pgtype.UUID `json:"assigned_by"`
	ApplicationID  pgtype.UUID `json:"application_id"`
}

func (q *Queries) AssignReviewer(ctx context.Context, arg AssignReviewerParams) (bool, error) {
	row := q.db.QueryRow(ctx, assignReviewer, arg.ReviewerUserID, arg.AssignedBy, arg.ApplicationID)
	var assigned bool
	err := row.Scan(&assigned)
	return assigned, err
}

const getOrganizerApplication = `-- name: GetOrganizerApplication :one
SELECT
    applications.id,
    applications.cycle_id,
    applications.form_id,
    forms.version AS form_version,
    applications.status,
    applications.submitted_at,
    applicants.id AS applicant_id,
    COALESCE(applications.applicant_email_snapshot, applicants.primary_email) AS applicant_email,
    applicants.display_name AS applicant_display_name,
    COALESCE(
        jsonb_object_agg(answers.question_key, answers.value_json)
            FILTER (WHERE answers.question_key IS NOT NULL),
        '{}'::jsonb
    )::text AS answers_json,
    applications.created_at,
    applications.updated_at
FROM ats.applications AS applications
JOIN ats.application_forms AS forms ON forms.id = applications.form_id
JOIN ats.users AS applicants ON applicants.id = applications.applicant_user_id
LEFT JOIN ats.application_answers AS answers ON answers.application_id = applications.id
WHERE applications.id = $1
  AND applications.status IN ('submitted', 'accepted', 'waitlisted', 'rejected')
GROUP BY
    applications.id,
    applications.cycle_id,
    applications.form_id,
    forms.version,
    applications.status,
    applications.submitted_at,
    applicants.id,
    applicants.primary_email,
    applicants.display_name,
    applications.created_at,
    applications.updated_at
`

type GetOrganizerApplicationRow struct {
	ID                   pgtype.UUID        `json:"id"`
	CycleID              pgtype.UUID        `json:"cycle_id"`
	FormID               pgtype.UUID        `json:"form_id"`
	FormVersion          int32              `json:"form_version"`
	Status               string             `json:"status"`
	SubmittedAt          pgtype.Timestamptz `json:"submitted_at"`
	ApplicantID          pgtype.UUID        `json:"applicant_id"`
	ApplicantEmail       string             `json:"applicant_email"`
	ApplicantDisplayName pgtype.Text        `json:"applicant_display_name"`
	AnswersJson          string             `json:"answers_json"`
	CreatedAt            pgtype.Timestamptz `json:"created_at"`
	UpdatedAt            pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) GetOrganizerApplication(ctx context.Context, id pgtype.UUID) (GetOrganizerApplicationRow, error) {
	row := q.db.QueryRow(ctx, getOrganizerApplication, id)
	var i GetOrganizerApplicationRow
	err := row.Scan(
		&i.ID,
		&i.CycleID,
		&i.FormID,
		&i.FormVersion,
		&i.Status,
		&i.SubmittedAt,
		&i.ApplicantID,
		&i.ApplicantEmail,
		&i.ApplicantDisplayName,
		&i.AnswersJson,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getReviewerApplication = `-- name: GetReviewerApplication :one
SELECT
    applications.id,
    applications.cycle_id,
    applications.form_id,
    forms.version AS form_version,
    applications.status,
    applications.submitted_at,
    applicants.id AS applicant_id,
    applicants.primary_email AS applicant_email,
    applicants.display_name AS applicant_display_name,
    COALESCE(
        jsonb_object_agg(answers.question_key, answers.value_json)
            FILTER (WHERE answers.question_key IS NOT NULL),
        '{}'::jsonb
    )::text AS answers_json,
    assignments.assigned_by,
    assignments.assigned_at,
    reviews.id AS review_id,
    reviews.status AS review_status,
    COALESCE(reviews.score_json, '{}'::jsonb)::text AS review_score_json,
    reviews.recommendation AS review_recommendation,
    reviews.internal_notes AS review_internal_notes,
    reviews.lock_version AS review_lock_version,
    reviews.submitted_at AS review_submitted_at,
    reviews.created_at AS review_created_at,
    reviews.updated_at AS review_updated_at,
    applications.created_at,
    applications.updated_at
FROM ats.applications AS applications
JOIN ats.application_forms AS forms ON forms.id = applications.form_id
JOIN ats.users AS applicants ON applicants.id = applications.applicant_user_id
LEFT JOIN ats.application_answers AS answers ON answers.application_id = applications.id
LEFT JOIN ats.review_assignments AS assignments
    ON assignments.application_id = applications.id
   AND assignments.reviewer_user_id = $2
LEFT JOIN ats.reviews AS reviews
    ON reviews.application_id = applications.id
   AND reviews.reviewer_user_id = $2
WHERE applications.id = $1
  AND applications.status = 'submitted'
GROUP BY
    applications.id,
    applications.cycle_id,
    applications.form_id,
    forms.version,
    applications.status,
    applications.submitted_at,
    applicants.id,
    applicants.primary_email,
    applicants.display_name,
    assignments.assigned_by,
    assignments.assigned_at,
    reviews.id,
    reviews.status,
    reviews.score_json,
    reviews.recommendation,
    reviews.internal_notes,
    reviews.lock_version,
    reviews.submitted_at,
    reviews.created_at,
    reviews.updated_at,
    applications.created_at,
    applications.updated_at
`

type GetReviewerApplicationParams struct {
	ID             pgtype.UUID `json:"id"`
	ReviewerUserID pgtype.UUID `json:"reviewer_user_id"`
}

type GetReviewerApplicationRow struct {
	ID                   pgtype.UUID        `json:"id"`
	CycleID              pgtype.UUID        `json:"cycle_id"`
	FormID               pgtype.UUID        `json:"form_id"`
	FormVersion          int32              `json:"form_version"`
	Status               string             `json:"status"`
	SubmittedAt          pgtype.Timestamptz `json:"submitted_at"`
	ApplicantID          pgtype.UUID        `json:"applicant_id"`
	ApplicantEmail       string             `json:"applicant_email"`
	ApplicantDisplayName pgtype.Text        `json:"applicant_display_name"`
	AnswersJson          string             `json:"answers_json"`
	AssignedBy           pgtype.UUID        `json:"assigned_by"`
	AssignedAt           pgtype.Timestamptz `json:"assigned_at"`
	ReviewID             pgtype.UUID        `json:"review_id"`
	ReviewStatus         pgtype.Text        `json:"review_status"`
	ReviewScoreJson      string             `json:"review_score_json"`
	ReviewRecommendation pgtype.Text        `json:"review_recommendation"`
	ReviewInternalNotes  pgtype.Text        `json:"review_internal_notes"`
	ReviewLockVersion    pgtype.Int4        `json:"review_lock_version"`
	ReviewSubmittedAt    pgtype.Timestamptz `json:"review_submitted_at"`
	ReviewCreatedAt      pgtype.Timestamptz `json:"review_created_at"`
	ReviewUpdatedAt      pgtype.Timestamptz `json:"review_updated_at"`
	CreatedAt            pgtype.Timestamptz `json:"created_at"`
	UpdatedAt            pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) GetReviewerApplication(ctx context.Context, arg GetReviewerApplicationParams) (GetReviewerApplicationRow, error) {
	row := q.db.QueryRow(ctx, getReviewerApplication, arg.ID, arg.ReviewerUserID)
	var i GetReviewerApplicationRow
	err := row.Scan(
		&i.ID,
		&i.CycleID,
		&i.FormID,
		&i.FormVersion,
		&i.Status,
		&i.SubmittedAt,
		&i.ApplicantID,
		&i.ApplicantEmail,
		&i.ApplicantDisplayName,
		&i.AnswersJson,
		&i.AssignedBy,
		&i.AssignedAt,
		&i.ReviewID,
		&i.ReviewStatus,
		&i.ReviewScoreJson,
		&i.ReviewRecommendation,
		&i.ReviewInternalNotes,
		&i.ReviewLockVersion,
		&i.ReviewSubmittedAt,
		&i.ReviewCreatedAt,
		&i.ReviewUpdatedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const grantReviewerRole = `-- name: GrantReviewerRole :one
WITH inserted AS (
    INSERT INTO ats.user_roles (user_id, role, created_by)
    SELECT users.id, 'reviewer', $1
    FROM ats.users
    WHERE users.id = $2
    ON CONFLICT (user_id, role) DO NOTHING
    RETURNING user_id
)
SELECT EXISTS (SELECT 1 FROM inserted) AS assigned
`

type GrantReviewerRoleParams struct {
	CreatedBy pgtype.UUID `json:"created_by"`
	UserID    pgtype.UUID `json:"user_id"`
}

func (q *Queries) GrantReviewerRole(ctx context.Context, arg GrantReviewerRoleParams) (bool, error) {
	row := q.db.QueryRow(ctx, grantReviewerRole, arg.CreatedBy, arg.UserID)
	var assigned bool
	err := row.Scan(&assigned)
	return assigned, err
}

const insertReviewAssignmentAudit = `-- name: InsertReviewAssignmentAudit :exec
INSERT INTO ats.audit_events (actor_user_id, event_type, subject_type, subject_id, metadata_json)
VALUES ($1, 'reviewer_assigned', 'application', $2, jsonb_build_object('reviewerUserId', $3::text))
`

type InsertReviewAssignmentAuditParams struct {
	ActorUserID    pgtype.UUID `json:"actor_user_id"`
	SubjectID      pgtype.UUID `json:"subject_id"`
	ReviewerUserID string      `json:"reviewer_user_id"`
}

func (q *Queries) InsertReviewAssignmentAudit(ctx context.Context, arg InsertReviewAssignmentAuditParams) error {
	_, err := q.db.Exec(ctx, insertReviewAssignmentAudit, arg.ActorUserID, arg.SubjectID, arg.ReviewerUserID)
	return err
}

const insertReviewSubmissionAudit = `-- name: InsertReviewSubmissionAudit :exec
INSERT INTO ats.audit_events (actor_user_id, event_type, subject_type, subject_id, metadata_json)
VALUES ($1, 'review_submitted', 'review', $2, jsonb_build_object('applicationId', $3::text))
`

type InsertReviewSubmissionAuditParams struct {
	ActorUserID   pgtype.UUID `json:"actor_user_id"`
	SubjectID     pgtype.UUID `json:"subject_id"`
	ApplicationID string      `json:"application_id"`
}

func (q *Queries) InsertReviewSubmissionAudit(ctx context.Context, arg InsertReviewSubmissionAuditParams) error {
	_, err := q.db.Exec(ctx, insertReviewSubmissionAudit, arg.ActorUserID, arg.SubjectID, arg.ApplicationID)
	return err
}

const insertReviewerRoleAudit = `-- name: InsertReviewerRoleAudit :exec
INSERT INTO ats.audit_events (actor_user_id, event_type, subject_type, subject_id, metadata_json)
VALUES ($1, 'reviewer_role_assigned', 'user', $2, jsonb_build_object('role', 'reviewer'))
`

type InsertReviewerRoleAuditParams struct {
	ActorUserID pgtype.UUID `json:"actor_user_id"`
	SubjectID   pgtype.UUID `json:"subject_id"`
}

func (q *Queries) InsertReviewerRoleAudit(ctx context.Context, arg InsertReviewerRoleAuditParams) error {
	_, err := q.db.Exec(ctx, insertReviewerRoleAudit, arg.ActorUserID, arg.SubjectID)
	return err
}

const listOrganizerApplications = `-- name: ListOrganizerApplications :many
SELECT
    applications.id,
    applications.cycle_id,
    applications.form_id,
    forms.version AS form_version,
    applications.status,
    applications.submitted_at,
    applicants.id AS applicant_id,
    COALESCE(applications.applicant_email_snapshot, applicants.primary_email) AS applicant_email,
    applicants.display_name AS applicant_display_name,
    COALESCE(
        jsonb_object_agg(answers.question_key, answers.value_json)
            FILTER (WHERE answers.question_key IS NOT NULL),
        '{}'::jsonb
    )::text AS answers_json,
    applications.created_at,
    applications.updated_at
FROM ats.applications AS applications
JOIN ats.application_forms AS forms ON forms.id = applications.form_id
JOIN ats.users AS applicants ON applicants.id = applications.applicant_user_id
LEFT JOIN ats.application_answers AS answers ON answers.application_id = applications.id
WHERE applications.status IN ('submitted', 'accepted', 'waitlisted', 'rejected')
  AND ($1::text = '' OR applications.status = $1::text)
  AND (
      $2::text = ''
      OR applications.id::text ILIKE '%' || $2::text || '%'
      OR applicants.primary_email ILIKE '%' || $2::text || '%'
      OR COALESCE(applicants.display_name, '') ILIKE '%' || $2::text || '%'
      OR EXISTS (
          SELECT 1
          FROM ats.application_answers AS searched_answers
          WHERE searched_answers.application_id = applications.id
            AND searched_answers.value_json::text ILIKE '%' || $2::text || '%'
      )
  )
GROUP BY
    applications.id,
    applications.cycle_id,
    applications.form_id,
    forms.version,
    applications.status,
    applications.submitted_at,
    applicants.id,
    applicants.primary_email,
    applicants.display_name,
    applications.created_at,
    applications.updated_at
ORDER BY applications.submitted_at DESC NULLS LAST, applications.created_at DESC
`

type ListOrganizerApplicationsParams struct {
	Status string `json:"status"`
	Search string `json:"search"`
}

type ListOrganizerApplicationsRow struct {
	ID                   pgtype.UUID        `json:"id"`
	CycleID              pgtype.UUID        `json:"cycle_id"`
	FormID               pgtype.UUID        `json:"form_id"`
	FormVersion          int32              `json:"form_version"`
	Status               string             `json:"status"`
	SubmittedAt          pgtype.Timestamptz `json:"submitted_at"`
	ApplicantID          pgtype.UUID        `json:"applicant_id"`
	ApplicantEmail       string             `json:"applicant_email"`
	ApplicantDisplayName pgtype.Text        `json:"applicant_display_name"`
	AnswersJson          string             `json:"answers_json"`
	CreatedAt            pgtype.Timestamptz `json:"created_at"`
	UpdatedAt            pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) ListOrganizerApplications(ctx context.Context, arg ListOrganizerApplicationsParams) ([]ListOrganizerApplicationsRow, error) {
	rows, err := q.db.Query(ctx, listOrganizerApplications, arg.Status, arg.Search)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListOrganizerApplicationsRow{}
	for rows.Next() {
		var i ListOrganizerApplicationsRow
		if err := rows.Scan(
			&i.ID,
			&i.CycleID,
			&i.FormID,
			&i.FormVersion,
			&i.Status,
			&i.SubmittedAt,
			&i.ApplicantID,
			&i.ApplicantEmail,
			&i.ApplicantDisplayName,
			&i.AnswersJson,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listReviewerApplications = `-- name: ListReviewerApplications :many
SELECT
    applications.id,
    applications.cycle_id,
    applications.form_id,
    forms.version AS form_version,
    applications.status,
    applications.submitted_at,
    applicants.id AS applicant_id,
    COALESCE(applications.applicant_email_snapshot, applicants.primary_email) AS applicant_email,
    applicants.display_name AS applicant_display_name,
    COALESCE(
        jsonb_object_agg(answers.question_key, answers.value_json)
            FILTER (WHERE answers.question_key IS NOT NULL),
        '{}'::jsonb
    )::text AS answers_json,
    assignments.assigned_by,
    assignments.assigned_at,
    reviews.id AS review_id,
    reviews.status AS review_status,
    COALESCE(reviews.score_json, '{}'::jsonb)::text AS review_score_json,
    reviews.recommendation AS review_recommendation,
    reviews.internal_notes AS review_internal_notes,
    reviews.lock_version AS review_lock_version,
    reviews.submitted_at AS review_submitted_at,
    reviews.created_at AS review_created_at,
    reviews.updated_at AS review_updated_at,
    applications.created_at,
    applications.updated_at
FROM ats.applications AS applications
JOIN ats.application_forms AS forms ON forms.id = applications.form_id
JOIN ats.users AS applicants ON applicants.id = applications.applicant_user_id
LEFT JOIN ats.application_answers AS answers ON answers.application_id = applications.id
LEFT JOIN ats.review_assignments AS assignments
    ON assignments.application_id = applications.id
   AND assignments.reviewer_user_id = $1
LEFT JOIN ats.reviews AS reviews
    ON reviews.application_id = applications.id
   AND reviews.reviewer_user_id = $1
WHERE applications.status = 'submitted'
GROUP BY
    applications.id,
    applications.cycle_id,
    applications.form_id,
    forms.version,
    applications.status,
    applications.submitted_at,
    applicants.id,
    applicants.primary_email,
    applicants.display_name,
    assignments.assigned_by,
    assignments.assigned_at,
    reviews.id,
    reviews.status,
    reviews.score_json,
    reviews.recommendation,
    reviews.internal_notes,
    reviews.lock_version,
    reviews.submitted_at,
    reviews.created_at,
    reviews.updated_at,
    applications.created_at,
    applications.updated_at
ORDER BY
    CASE WHEN assignments.assigned_at IS NULL THEN 1 ELSE 0 END,
    assignments.assigned_at DESC NULLS LAST,
    applications.submitted_at DESC,
    applications.created_at DESC
`

type ListReviewerApplicationsRow struct {
	ID                   pgtype.UUID        `json:"id"`
	CycleID              pgtype.UUID        `json:"cycle_id"`
	FormID               pgtype.UUID        `json:"form_id"`
	FormVersion          int32              `json:"form_version"`
	Status               string             `json:"status"`
	SubmittedAt          pgtype.Timestamptz `json:"submitted_at"`
	ApplicantID          pgtype.UUID        `json:"applicant_id"`
	ApplicantEmail       string             `json:"applicant_email"`
	ApplicantDisplayName pgtype.Text        `json:"applicant_display_name"`
	AnswersJson          string             `json:"answers_json"`
	AssignedBy           pgtype.UUID        `json:"assigned_by"`
	AssignedAt           pgtype.Timestamptz `json:"assigned_at"`
	ReviewID             pgtype.UUID        `json:"review_id"`
	ReviewStatus         pgtype.Text        `json:"review_status"`
	ReviewScoreJson      string             `json:"review_score_json"`
	ReviewRecommendation pgtype.Text        `json:"review_recommendation"`
	ReviewInternalNotes  pgtype.Text        `json:"review_internal_notes"`
	ReviewLockVersion    pgtype.Int4        `json:"review_lock_version"`
	ReviewSubmittedAt    pgtype.Timestamptz `json:"review_submitted_at"`
	ReviewCreatedAt      pgtype.Timestamptz `json:"review_created_at"`
	ReviewUpdatedAt      pgtype.Timestamptz `json:"review_updated_at"`
	CreatedAt            pgtype.Timestamptz `json:"created_at"`
	UpdatedAt            pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) ListReviewerApplications(ctx context.Context, reviewerUserID pgtype.UUID) ([]ListReviewerApplicationsRow, error) {
	rows, err := q.db.Query(ctx, listReviewerApplications, reviewerUserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListReviewerApplicationsRow{}
	for rows.Next() {
		var i ListReviewerApplicationsRow
		if err := rows.Scan(
			&i.ID,
			&i.CycleID,
			&i.FormID,
			&i.FormVersion,
			&i.Status,
			&i.SubmittedAt,
			&i.ApplicantID,
			&i.ApplicantEmail,
			&i.ApplicantDisplayName,
			&i.AnswersJson,
			&i.AssignedBy,
			&i.AssignedAt,
			&i.ReviewID,
			&i.ReviewStatus,
			&i.ReviewScoreJson,
			&i.ReviewRecommendation,
			&i.ReviewInternalNotes,
			&i.ReviewLockVersion,
			&i.ReviewSubmittedAt,
			&i.ReviewCreatedAt,
			&i.ReviewUpdatedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const submitReview = `-- name: SubmitReview :one
UPDATE ats.reviews AS reviews
SET status = 'submitted',
    submitted_at = CURRENT_TIMESTAMP,
    lock_version = reviews.lock_version + 1,
    updated_at = CURRENT_TIMESTAMP
FROM ats.applications AS applications
WHERE reviews.application_id = applications.id
  AND reviews.application_id = $1
  AND reviews.reviewer_user_id = $2
  AND reviews.status = 'draft'
  AND reviews.lock_version = $3::integer
  AND applications.status = 'submitted'
RETURNING reviews.id
`

type SubmitReviewParams struct {
	ApplicationID  pgtype.UUID `json:"application_id"`
	ReviewerUserID pgtype.UUID `json:"reviewer_user_id"`
	LockVersion    int32       `json:"lock_version"`
}

func (q *Queries) SubmitReview(ctx context.Context, arg SubmitReviewParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, submitReview, arg.ApplicationID, arg.ReviewerUserID, arg.LockVersion)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}

const updateReviewDraft = `-- name: UpdateReviewDraft :one
INSERT INTO ats.reviews (
    application_id,
    reviewer_user_id,
    score_json,
    recommendation,
    internal_notes,
    lock_version
)
SELECT
    $1,
    $2,
    $3::jsonb,
    $4::text,
    NULLIF($5::text, ''),
    1
FROM ats.applications AS applications
WHERE applications.id = $1
  AND applications.status = 'submitted'
  AND $6::integer = 0
ON CONFLICT (application_id, reviewer_user_id) DO UPDATE
SET score_json = EXCLUDED.score_json,
    recommendation = EXCLUDED.recommendation,
    internal_notes = EXCLUDED.internal_notes,
    lock_version = ats.reviews.lock_version + 1,
    updated_at = CURRENT_TIMESTAMP
WHERE ats.reviews.status = 'draft'
  AND ats.reviews.lock_version = $6::integer
RETURNING id
`

type UpdateReviewDraftParams struct {
	ApplicationID  pgtype.UUID `json:"application_id"`
	ReviewerUserID pgtype.UUID `json:"reviewer_user_id"`
	ScoreJson      []byte      `json:"score_json"`
	Recommendation string      `json:"recommendation"`
	InternalNotes  string      `json:"internal_notes"`
	LockVersion    int32       `json:"lock_version"`
}

func (q *Queries) UpdateReviewDraft(ctx context.Context, arg UpdateReviewDraftParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, updateReviewDraft,
		arg.ApplicationID,
		arg.ReviewerUserID,
		arg.ScoreJson,
		arg.Recommendation,
		arg.InternalNotes,
		arg.LockVersion,
	)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}

const userExists = `-- name: UserExists :one
SELECT EXISTS (
    SELECT 1
    FROM ats.users
    WHERE id = $1
) AS user_exists
`

func (q *Queries) UserExists(ctx context.Context, id pgtype.UUID) (bool, error) {
	row := q.db.QueryRow(ctx, userExists, id)
	var user_exists bool
	err := row.Scan(&user_exists)
	return user_exists, err
}

const userHasReviewerRole = `-- name: UserHasReviewerRole :one
SELECT EXISTS (
    SELECT 1
    FROM ats.user_roles
    WHERE user_id = $1
      AND role = 'reviewer'
) AS has_reviewer_role
`

func (q *Queries) UserHasReviewerRole(ctx context.Context, userID pgtype.UUID) (bool, error) {
	row := q.db.QueryRow(ctx, userHasReviewerRole, userID)
	var has_reviewer_role bool
	err := row.Scan(&has_reviewer_role)
	return has_reviewer_role, err
}
